import { defineConfig } from "tsup";

export default defineConfig({
	entry: [
		"src/index.ts",
		"src/adapters/index.ts",
		"src/adapters/observe-storage.ts",
		"src/adapters/react.ts",
		"src/adapters/solid.ts",
		"src/adapters/svelte.ts",
		"src/adapters/vue.ts",
		"src/composition/index.ts",
		"src/cqrs/index.ts",
		"src/core/index.ts",
		"src/data/index.ts",
		"src/data-structures/index.ts",
		"src/graph/index.ts",
		"src/inspection/boundary.ts",
		"src/messaging/index.ts",
		"src/operators/index.ts",
		"src/orchestration/index.ts",
		"src/patterns/index.ts",
		"src/render/index.ts",
		"src/solutions/index.ts",
		"src/solutions/reactive-layout/index.ts",
		"src/solutions/reactive-layout/browser/index.ts",
		"src/solutions/reactive-layout/node-canvas/index.ts",
		"src/solutions/reactive-layout/react-native/index.ts",
		"src/solutions/reactive-layout/skia/index.ts",
		"src/sources/browser.ts",
		"src/sources/index.ts",
		"src/sources/node.ts",
		"src/storage/index.ts",
		"src/storage/node.ts",
		"src/storage/browser.ts",
		"src/testing/index.ts",
		"src/work-queue/index.ts",
	],
	format: ["esm", "cjs"],
	dts: true,
	clean: true,
	sourcemap: true,
});
