import { defineConfig } from "tsup";

export default defineConfig({
	entry: [
		"src/index.ts",
		"src/adapters/index.ts",
		"src/adapters/nestjs.ts",
		"src/adapters/nestjs/microservices.ts",
		"src/adapters/nestjs/native.ts",
		"src/adapters/nestjs/websockets.ts",
		"src/adapters/observe-storage.ts",
		"src/adapters/react.ts",
		"src/adapters/solid.ts",
		"src/adapters/svelte.ts",
		"src/adapters/vue.ts",
		"src/composition/index.ts",
		"src/cqrs/index.ts",
		"src/cqrs/messaging.ts",
		"src/cqrs/work-queue.ts",
		"src/core/index.ts",
		"src/data/index.ts",
		"src/data-structures/index.ts",
		"src/graph/index.ts",
		"src/inspection/boundary.ts",
		"src/executors/tool-provider.ts",
		"src/executors/execution-environment.ts",
		"src/executors/local-container-postgresql.ts",
		"src/executors/managed-cloud-postgresql.ts",
		"src/executors/customer-hosted-postgresql.ts",
		"src/executors/tool-provider-adapters.ts",
		"src/executors/postgresql-tool-provider.ts",
		"src/executors/tool-provider-runtime.ts",
		"src/executors/work-queue.ts",
		"src/memory/index.ts",
		"src/memory/semantic/index.ts",
		"src/messaging/index.ts",
		"src/operators/index.ts",
		"src/orchestration/index.ts",
		"src/orchestration/messaging.ts",
		"src/orchestration/work-queue.ts",
		"src/patterns/event-flow.ts",
		"src/patterns/index.ts",
		"src/render/index.ts",
		"src/scoring/index.ts",
		"src/solutions/agentic-memory/browser.ts",
		"src/solutions/agentic-memory/index.ts",
		"src/solutions/agentic-memory/node.ts",
		"src/solutions/agentic-work-item-memory/index.ts",
		"src/solutions/agentic-work-item-memory-application/index.ts",
		"src/solutions/index.ts",
		"src/solutions/work-item/index.ts",
		"src/solutions/work-item/actions.ts",
		"src/solutions/work-item/scheduling.ts",
		"src/solutions/work-item/work-queue.ts",
		"src/solutions/reactive-layout/index.ts",
		"src/solutions/reactive-layout/browser/index.ts",
		"src/solutions/reactive-layout/node-canvas/index.ts",
		"src/solutions/reactive-layout/react-native/index.ts",
		"src/solutions/reactive-layout/skia/index.ts",
		"src/sources/browser.ts",
		"src/sources/index.ts",
		"src/sources/node.ts",
		"src/storage/index.ts",
		"src/storage/node.ts",
		"src/storage/browser.ts",
		"src/testing/index.ts",
		"src/work-queue/index.ts",
	],
	format: ["esm", "cjs"],
	dts: true,
	clean: true,
	sourcemap: true,
});
