export {
	type FactId,
	type FactStore,
	type KnowledgeAssertion,
	type KnowledgeAssertionObject,
	type KnowledgeAssertionStrictJsonValue,
	type KnowledgeAssertionSubject,
	type MemoryAnswer,
	type MemoryFragment,
	type MemoryFragmentValidation,
	type MemoryQuery,
	memoryFragmentMatchesQuery,
	memoryFragmentValidAt,
	type ShardByTenantConfig,
	type ShardByTenantOptions,
	type ShardKey,
	type StoreReadHandle,
	validateMemoryFragment,
} from "../../patterns/semantic-memory.js";
