"""Render saved offline evidence; does not execute a graph or create runtime authority."""
import hashlib
import html
import json
from pathlib import Path

base = Path(__file__).resolve().parent
root = base.parents[2]
read = lambda name: json.loads((base / name).read_text())
demo, source, mutations = map(read, ['demo.json', 'source-binding.json', 'mutations.json'])
assert demo['mode'] == 'offline-simulation' and not demo['realInboxIO']
assert source['verified'] and source['realInboxIO'] == 0
assert source['results']['control']['topology'] == source['results']['fresh']['topology']
assert all(not source['results'][key]['calls'] for key in ['staleBoth', 'staleSource', 'staleRuntime'])
assert len([r for r in mutations['results'] if r['verdict'] == 'behavior-killed']) == 9
# Bind every baseline bundle input to the current bytes; transformed candidate bytes intentionally differ.
for item in source['bundles'][0]['inputs']:
    if item['path'] == 'source-binding-worker.ts':
        continue  # Generated by the qualified tool; its hash is carried in the bundle receipt.
    path = root / item['path']
    assert path.is_file(), item['path']
    assert hashlib.sha256(path.read_bytes()).hexdigest() == item['sha256'], item['path']
esc = html.escape
pretty = lambda value: esc(json.dumps(value, ensure_ascii=False, indent=2))
rows = ''.join(f'<tr><td>{esc(n["id"])}</td><td>{esc(n.get("factory", ""))}</td><td>{esc(", ".join(n.get("deps", [])))}</td></tr>' for n in demo['maintainer']['topology']['nodes'])
changes = ''.join(f'<tr><td>{"修改后" if b["candidate"] else "基线"}</td><td><code>{esc(b["binding"]["sourceDigest"])}</code></td><td><code>{esc(b["binding"]["runtimeDigest"])}</code></td></tr>' for b in source['bundles'])
page = f'''<!doctype html><html lang="zh"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Spending · 分层入口离线审阅</title>
<style>body{{font:16px/1.65 system-ui,sans-serif;background:#f4f5f2;color:#172321;max-width:1100px;margin:40px auto;padding:0 24px}}h1{{font-size:32px}}section,details{{background:white;border:1px solid #d6ded6;border-radius:8px;padding:24px;margin:18px 0}}summary{{cursor:pointer;font-weight:650}}pre{{white-space:pre-wrap;overflow-wrap:anywhere;background:#f4f5f2;padding:16px;font-size:13px}}table{{border-collapse:collapse;width:100%;font-size:13px}}td,th{{padding:10px;border-bottom:1px solid #d6ded6;text-align:left;overflow-wrap:anywhere}}code{{overflow-wrap:anywhere}}a{{color:#12634c}}.tag{{color:#76521d}}small{{color:#53635a}}</style>
<p class="tag">离线模拟 / 已保存的执行观察 / 非实时运行界面</p><h1>一个运行实例，逐层查看</h1><p>普通组件只收到五个业务端口；框架拿原能力；维护者下钻到同一个 Graph。展开下面的内容不会创建实例或执行 I/O。</p>
<section><h2>普通用户 · 业务结果</h2><pre>{esc(demo['ordinary']['finalDisplay'])}</pre><p>这些是各端口最近可观察值，不是原子快照，也不是独立证明。缺少 coverage 或 issues 当前值会明确显示缺失。</p><p><a href="demo.json">完整离线运行观察</a> · <a href="../../../examples/spending-alerts/causal-graded-demo.ts">应用接入源码</a></p></section>
<details><summary>框架作者 · 原能力与运行责任</summary><pre>{pretty(demo['framework'])}</pre><p>identity、execution、retained 共享原引用。它们没有 publish/feed 方法。应用保留 owner；退订只结束观察。</p><pre>{pretty(demo['observations'])}</pre></details>
<details><summary>Library 维护者 · 原图、请求与结果</summary><p>{demo['maintainer']['nodes']} 个节点，{demo['maintainer']['edges']} 条边。以下数据来自本次 appGraph.describe()。</p><table><thead><tr><th>节点 ID</th><th>Factory</th><th>依赖</th></tr></thead><tbody>{rows}</tbody></table><h3>本次 fixture 请求证据</h3><pre>{pretty(demo['evidence'])}</pre><p>fixture digest 不是加载源码认证。下面的独立源码试验是另一条明确绑定的证据，不能借它替换本次 fixture 身份。</p></details>
<section><h2>实现、来源、后果：分别核实</h2><p>本次离线 source-binding 试验把 vendorStats 内部 map 表达式等价改写；相同拓扑仍能看到源码与 bundle digest 变化。此结论只覆盖该改写与其测试输入。</p><table><thead><tr><th>版本</th><th>源码闭包</th><th>运行 bundle</th></tr></thead><tbody>{changes}</tbody></table><h3>修改来源</h3><pre>{pretty(source['provenance'])}</pre><p>以上为工具记录的实验来源，不是外部签名身份认证。应用 demo 本身没有算法作者认证。</p><h3>独立后果验证</h3><p>独立 plain-code oracle 核对 payload；旧 source/runtime/两者绑定分别阻断执行；新绑定接受。9 个真实代码 mutation 被行为断言捕获。</p><p><a href="source-binding.json">源码／绑定／旧证据结果</a> · <a href="mutations.json">真实 runtime mutation</a> · <a href="receipt.json">本批复核清单与文件哈希</a></p></section>
<section><h2>审阅问题</h2><ol><li>启动成功时，运行是否已经结束？</li><li>展示组件退出后，谁保留未结义务？</li><li>拓扑相同，能否说明节点实现没变？</li><li>作者来源、结果等价与执行许可分别由什么支持？</li><li>普通组件要理解哪些输入装配细节？需要下钻时能否找到原节点？</li></ol><p>这是开发审阅包。B121 的真实 human/agent 理解度试验尚未执行；正式试验需另用隔离答案键。</p></section>
<small>私有 consumer 示例；公共入口、真实宿主资格及正式性能资格不在本批完成声明内。</small></html>'''
(base / 'review.html').write_text(page)
print('saved review rendered; baseline source bytes verified')
