/**
 * @graphrefly/ts public TypeScript package.
 *
 * Exports the graph runtime, operators, sources, storage helpers, adapters,
 * renderers, testing helpers, and focused solution modules.
 */

export {
	type OpenPersistentReactiveIndexOptions,
	type OpenPersistentReactiveListOptions,
	type OpenPersistentReactiveLogOptions,
	type OpenPersistentReactiveMapOptions,
	openPersistentReactiveIndex,
	openPersistentReactiveList,
	openPersistentReactiveLog,
	openPersistentReactiveMap,
	type PersistentReactiveIndex,
	type PersistentReactiveList,
	type PersistentReactiveLog,
	type PersistentReactiveMap,
	type PersistReactiveCollectionOptions,
	persistReactiveCollection,
	type ReactiveCollectionPersistenceCursor,
	type ReactiveCollectionPersistenceError,
	type ReactiveCollectionPersistenceHandle,
	type ReactiveCollectionPersistenceStatus,
} from "./adapters/reactive-collection-storage.js";
export { type BatchCtx, batch } from "./batch/batch.js";
export type {
	Ctx,
	CtxState,
	NodeFn,
	RewireNext,
	Sink,
	TerminalData,
	WaveData,
} from "./ctx/types.js";
export {
	depBatch,
	depCount,
	depLatest,
	depTerminal,
	depWaves,
	isTerminalComplete,
	isTerminalError,
	isTerminalNone,
	terminalErrorValue,
} from "./ctx/types.js";
export type { DataError, DataIssue, DataOk, DataResult } from "./data/index.js";
export {
	restoreReactiveIndex,
	restoreReactiveList,
	restoreReactiveLog,
	restoreReactiveMap,
} from "./data-structures/persistence.js";
export {
	Dispatcher,
	defaultDispatcher,
	type Handle,
	type HandleStat,
	type Pool,
	type PoolKind,
} from "./dispatcher/index.js";
export {
	canonicalTopologyBytes,
	canonicalTopologyJson,
	GRAPH_BLUEPRINT_VERSION,
	GRAPH_BLUEPRINT_VERSION_V1,
	type GraphBlueprint,
	type GraphBlueprintDiagnosticCode,
	type GraphBlueprintDiagnosticIssue,
	type GraphBlueprintDiagnostics,
	type GraphBlueprintEvidence,
	type GraphBlueprintHash,
	type GraphBlueprintHashInput,
	type GraphBlueprintHashOptions,
	type GraphBlueprintJson,
	type GraphBlueprintOptions,
	type GraphBlueprintProvenance,
	type GraphBlueprintVersion,
	graphBlueprintDiagnostics,
	type LegacyGraphBlueprint,
	type NormalizedGraphTopologyNode,
	type NormalizedGraphTopologySnapshot,
	normalizeTopology,
	withBlueprintHash,
	withBlueprintProvenance,
} from "./graph/blueprint.js";
export {
	diffGraphBlueprints,
	GRAPH_BLUEPRINT_DELTA_VERSION,
	type GraphBlueprintDelta,
	type GraphBlueprintDeltaEvent,
	type GraphBlueprintTopologyPath,
	parseGraphBlueprint,
	verifyBlueprintHash,
} from "./graph/blueprint-evidence.js";
export {
	type CascadingCacheEvent,
	type CascadingCachePolicy,
	type CascadingCacheStatus,
	type ReactiveCascadingCache,
	type ReactiveCascadingCacheOptions,
	reactiveCascadingCache,
} from "./graph/cascading-cache.js";
export {
	GRAPH_CHECKPOINT_VERSION,
	type GraphCheckpoint,
	type GraphCheckpointEdge,
	type GraphCheckpointFactory,
	type GraphCheckpointJson,
	type GraphCheckpointMount,
	type GraphCheckpointNode,
	type GraphCheckpointTerminal,
	type GraphCheckpointValue,
	type GraphCheckpointVersion,
} from "./graph/checkpoint.js";
export {
	buffer,
	bufferCount,
	combine,
	combineLatest,
	concat,
	race,
	sample,
	takeUntil,
	withLatestFrom,
	zip,
} from "./graph/combinators.js";
export {
	type DescribeChangeset,
	type DescribeEvent,
	type PipeOperator,
	pipe,
	type Stratified,
	type StratifyOptions,
	type StratifyRule,
	stratify,
	stratifyBranch,
	topologyDiff,
} from "./graph/composition.js";
export type {
	IndexChange,
	ListChange,
	LogChange,
	MapChange,
} from "./graph/data-structures/change.js";
export type { ReactiveView } from "./graph/data-structures/core.js";
export {
	type IndexRow,
	type ReactiveIndex,
	type ReactiveIndexCapacityOrder,
	type ReactiveIndexCapacityPolicy,
	type ReactiveIndexOpt,
	type ReactiveIndexOptions,
	reactiveIndex,
} from "./graph/data-structures/reactive-index.js";
export {
	type ReactiveList,
	type ReactiveListOpt,
	type ReactiveListOptions,
	reactiveList,
} from "./graph/data-structures/reactive-list.js";
export {
	mergeReactiveLogs,
	type ReactiveLog,
	type ReactiveLogOptions,
	reactiveLog,
	scanLog,
} from "./graph/data-structures/reactive-log.js";
export {
	type ReactiveMap,
	type ReactiveMapOpt,
	type ReactiveMapOptions,
	type ReactiveMapRetentionEntry,
	type ReactiveMapRetentionPolicy,
	reactiveMap,
} from "./graph/data-structures/reactive-map.js";
export type {
	DescribeEdge,
	DescribeNode,
	DescribeOpts,
	DescribeSnapshot,
	GraphTopologyEdge,
	GraphTopologyNode,
	GraphTopologySnapshot,
} from "./graph/describe.js";
export {
	type CausalChain,
	type CausalStep,
	type ExplainPathOptions,
	type ExplainPathReason,
	explainPath,
	type IslandReport,
	type ReachableDirection,
	type ReachableOptions,
	type ReachableResult,
	reachable,
	type ValidateNoIslandsResult,
	validateNoIslands,
} from "./graph/diagnostics.js";
export {
	type DriverCancel,
	type DriverResult,
	domWebSocketDriver,
	EnvironmentDrivers,
	type EnvironmentDriversInit,
	type FetchLike,
	type FetchResponseLike,
	fetchHttpDriver,
	type HttpRequest,
	type HttpResponse,
	type LocalHttpDriver,
	type LocalProcessDriver,
	type LocalSseDriver,
	type LocalWebhookDriver,
	type LocalWebSocketDriver,
	type ProcessCommand,
	type ProcessResult,
	type SseDriverEvent,
	type SseEvent,
	type SseRequest,
	type WebhookDriverEvent,
	type WebhookEvent,
	type WebhookRegistration,
	type WebSocketConstructorLike,
	type WebSocketDriverEvent,
	type WebSocketEvent,
	type WebSocketLike,
	type WebSocketRequest,
	type WebSocketSend,
	type WebSocketSendResult,
	type WebSocketSessionHandle,
} from "./graph/environment.js";
export {
	type DerivedFn,
	type EffectFn,
	Graph,
	type GraphOptions,
	graph,
	StateNode,
	type SugarOpts,
	type TopologyGroup,
	type TopologyGroupOptions,
	type TopologyGroupReleaseOptions,
} from "./graph/graph.js";
export {
	concatMap,
	exhaustMap,
	flatMap,
	type MergeMapOptions,
	mergeMap,
	type Project,
	repeat,
	switchMap,
} from "./graph/higher-order.js";
export {
	coalesceObserve,
	filterObserve,
	type NodeProfile,
	type ObserveEvent,
	type ObserveEventEquals,
	type ObservePredicate,
	type ObserveStream,
	type Profile,
	type TopologyEvent,
	type TopologyEventKind,
	type TopologyStream,
} from "./graph/inspect.js";
export {
	catchError,
	type DefineOpts,
	type Definition,
	define,
	distinctUntilChanged,
	elementAt,
	filter,
	find,
	first,
	initNode,
	last,
	map,
	merge,
	type Operator,
	onFirstData,
	pairwise,
	type RestoreRegistryEntry,
	reduce,
	rescue,
	restoreRegistry,
	type SettleOpts,
	scan,
	settle,
	skip,
	type TapObserver,
	take,
	takeWhile,
	tap,
	tapFirst,
	type ValveOpts,
	valve,
} from "./graph/operators.js";
export type {
	CapacityPolicy,
	OrderedCapacityPolicy,
	ReactiveOpt,
	RetentionPolicy,
	ViewCachePolicy,
} from "./graph/policies/types.js";
export {
	blueprintToMermaid,
	type DescribeToAsciiOptions,
	type DescribeToD2Options,
	type DescribeToJsonOptions,
	type DescribeToMermaidOptions,
	type DescribeToMermaidUrlOptions,
	type DescribeToPrettyOptions,
	type DiagramDirection,
	describeToAscii,
	describeToD2,
	describeToJson,
	describeToMermaid,
	describeToMermaidUrl,
	describeToPretty,
	type GraphBlueprintToMermaidOptions,
	type MermaidLiveTheme,
	type MermaidLiveUrlOptions,
	mermaidLiveUrl,
} from "./graph/render.js";
export {
	type BackoffPolicy,
	backoffDelayMs,
	nextRetryDelayMs,
	noBackoff,
	type RetryPolicy,
	type RetryState,
	type RetryStatus,
	retryPolicy,
	shouldRetry,
} from "./graph/resilience.js";
export {
	defaultRestoreRegistry,
	type GraphRestoreDefinition,
	type GraphRestoreDescriptor,
	type GraphRestoreDescriptorContext,
	type GraphRestoreEntry,
	type GraphRestoreRegistry,
	mapRestoreDescriptor,
	type RestoreGraphOptions,
	restoreGraph,
	stateRestoreDescriptor,
	takeRestoreDescriptor,
	timerRestoreDescriptor,
} from "./graph/restore.js";
export {
	type AsyncSourceOpts,
	type CronSchedule,
	type EventListenerOptionsLike,
	type EventTargetLike,
	empty,
	type FromCronOptions,
	type FromEventOptions,
	firstValueFrom,
	fromAny,
	fromAsyncIter,
	fromCron,
	fromEvent,
	fromHttp,
	fromHttpWithOptions,
	fromIter,
	fromProcess,
	fromPromise,
	fromPushNotification,
	fromSSE,
	fromSSEWithOptions,
	fromTimer,
	fromWebhook,
	fromWebhookWithOptions,
	fromWebSocket,
	fromWebSocketWithOptions,
	interval,
	matchesCron,
	type NodeInput,
	never,
	of,
	type PushRegister,
	type PushUnsubscribe,
	parseCron,
	runProcess,
	runProcessWithOptions,
	type SingleFromAnyOptions,
	singleFromAny,
	type TimerSourceOpts,
	throwError,
	timer,
} from "./graph/sources.js";
export {
	audit,
	auditTime,
	bufferTime,
	debounce,
	debounceTime,
	delay,
	throttle,
	throttleTime,
	timeout,
} from "./graph/time.js";
export {
	type WorkerDerivedBackend,
	type WorkerDerivedCancel,
	type WorkerDerivedJob,
	type WorkerDerivedOptions,
	type WorkerDerivedSettle,
	type WorkerDerivedSettlement,
	workerDerived,
} from "./graph/worker.js";
export {
	assertStrictJsonObject,
	assertStrictJsonValue,
	type StrictJsonObject,
	type StrictJsonScalar,
	type StrictJsonValue,
	strictCanonicalJsonBytes,
} from "./json/codec.js";
export { dynamicNode, Node, type NodeOptions, node, type Status } from "./node/node.js";
export {
	defaultNodeVersionHash,
	type NodeVersion,
	type NodeVersionHashFn,
	type NodeVersioningLevel,
	type NodeVersioningPolicy,
	type NodeVersionJson,
	type NodeVersionV0,
	type NodeVersionV1,
} from "./node/versioning.js";
export {
	type KnowledgeAssertionStrictJsonValue,
	type KnowledgeGraphCursor,
	type KnowledgeGraphEntity,
	type KnowledgeGraphError,
	type KnowledgeGraphErrorCode,
	type KnowledgeGraphIndex,
	type KnowledgeGraphPolicy,
	type KnowledgeGraphReducerBundle,
	type KnowledgeGraphReducerBundleOptions,
	type KnowledgeGraphRelation,
	type KnowledgeGraphSnapshot,
	type KnowledgeGraphStatus,
	type KnowledgeGraphStatusState,
	type KnowledgeGraphTopic,
	knowledgeGraphReducerBundle,
} from "./patterns/index.js";
export * from "./protocol/messages.js";
export {
	AGENTIC_MEMORY_APPLICATION_DECISION_STORE_FRAME_FORMAT,
	AGENTIC_MEMORY_APPLICATION_EVIDENCE_STORE_FRAME_FORMAT,
	AGENTIC_MEMORY_COMMITTED_FACT_BATCH_FORMAT,
	AGENTIC_MEMORY_COMMITTED_FACT_FORMAT,
	AGENTIC_MEMORY_COMMITTED_FACT_IDENTITY_ALGORITHM,
	AGENTIC_MEMORY_COMMITTED_FACT_LOG_BACKEND_CURSOR_KIND,
	AGENTIC_MEMORY_COMMITTED_FACT_MATERIAL_IDENTITY_ALGORITHM,
	AGENTIC_MEMORY_COMMITTED_FACT_SNAPSHOT_FORMAT,
	AGENTIC_MEMORY_COMMITTED_FACT_VERSION,
	AGENTIC_MEMORY_DURABILITY_ADVANCE_ON_COMMITTED_OR_DUPLICATE_POLICY,
	AGENTIC_MEMORY_FACT_STREAM_CURSOR_KIND,
	AGENTIC_MEMORY_RECORD_APPLICATION_MATERIAL_IDENTITY_ALGORITHM,
	AGENTIC_MEMORY_RECORD_FRAME_FORMAT,
	AGENTIC_MEMORY_RECORD_FRAME_VERSION,
	AGENTIC_MEMORY_RECORD_STORE_FRAME_FORMAT,
	AGENTIC_MEMORY_STORE_FRAME_VERSION,
	type AgenticMemoryApplicationDecisionStoreFrame,
	type AgenticMemoryApplicationDecisionStoreFrameDecision,
	type AgenticMemoryApplicationEvidenceStoreFrame,
	type AgenticMemoryApplicationEvidenceStoreFrameBundle,
	type AgenticMemoryApplicationEvidenceStoreFrameBundleOptions,
	type AgenticMemoryApplicationEvidenceStoreFrameProjection,
	type AgenticMemoryArtifactKind,
	type AgenticMemoryBundle,
	type AgenticMemoryBundleOptions,
	type AgenticMemoryCommittedApplicationDecisionMaterial,
	type AgenticMemoryCommittedApplicationEvidenceMaterial,
	type AgenticMemoryCommittedFact,
	type AgenticMemoryCommittedFactBatch,
	type AgenticMemoryCommittedFactCoordinates,
	type AgenticMemoryCommittedFactCursor,
	type AgenticMemoryCommittedFactFamily,
	type AgenticMemoryCommittedFactIdentity,
	type AgenticMemoryCommittedFactLog,
	type AgenticMemoryCommittedFactLogAppendAttemptCursor,
	type AgenticMemoryCommittedFactLogAppendAttemptOptions,
	type AgenticMemoryCommittedFactLogAppendAttemptResult,
	type AgenticMemoryCommittedFactLogBackend,
	type AgenticMemoryCommittedFactLogBackendAppendResult,
	type AgenticMemoryCommittedFactLogBackendAuditEntry,
	type AgenticMemoryCommittedFactLogBackendCapability,
	type AgenticMemoryCommittedFactLogBackendCursor,
	type AgenticMemoryCommittedFactLogBackendReadResult,
	type AgenticMemoryCommittedFactLogBackendStatus,
	type AgenticMemoryCommittedFactLogBackendStatusState,
	type AgenticMemoryCommittedFactLogRuntimePersistenceAuditEntry,
	type AgenticMemoryCommittedFactLogStartupReadCursor,
	type AgenticMemoryCommittedFactLogStartupReadOptions,
	type AgenticMemoryCommittedFactLogStartupReadResult,
	type AgenticMemoryCommittedFactMaterial,
	type AgenticMemoryCommittedFactMaterialIdentity,
	type AgenticMemoryCommittedFactMaterialization,
	type AgenticMemoryCommittedFactMaterializationAuditEntry,
	type AgenticMemoryCommittedFactMaterializationCursor,
	type AgenticMemoryCommittedFactMaterializationStatus,
	type AgenticMemoryCommittedFactReadMaterializationAuditEntry,
	type AgenticMemoryCommittedFactReadMaterializationBundle,
	type AgenticMemoryCommittedFactReadMaterializationBundleOptions,
	type AgenticMemoryCommittedFactReadMaterializationCursor,
	type AgenticMemoryCommittedFactReadMaterializationProjection,
	type AgenticMemoryCommittedFactReadMaterializationStatus,
	type AgenticMemoryCommittedFactReadMaterializationStatusState,
	type AgenticMemoryCommittedFactReadOptions,
	type AgenticMemoryCommittedFactReadResult,
	type AgenticMemoryCommittedFactSnapshot,
	type AgenticMemoryCommittedPriorEvidenceMaterial,
	type AgenticMemoryCommittedRecordMaterial,
	type AgenticMemoryConsolidationApplicationBundle,
	type AgenticMemoryConsolidationApplicationBundleOptions,
	type AgenticMemoryConsolidationBundle,
	type AgenticMemoryConsolidationBundleOptions,
	type AgenticMemoryConsolidationCommand,
	type AgenticMemoryConsolidationCursor,
	type AgenticMemoryConsolidationError,
	type AgenticMemoryConsolidationErrorCode,
	type AgenticMemoryConsolidationOutcome,
	type AgenticMemoryConsolidationRecordDraft,
	type AgenticMemoryConsolidationRequest,
	type AgenticMemoryConsolidationResult,
	type AgenticMemoryConsolidationSnapshot,
	type AgenticMemoryConsolidationStatus,
	type AgenticMemoryContext,
	type AgenticMemoryContextAttribution,
	type AgenticMemoryContextEntry,
	type AgenticMemoryContextPackingBundle,
	type AgenticMemoryContextPackingBundleOptions,
	type AgenticMemoryContextPackingCursor,
	type AgenticMemoryContextPackingError,
	type AgenticMemoryContextPackingErrorCode,
	type AgenticMemoryContextPackingPolicy,
	type AgenticMemoryContextPackingSnapshot,
	type AgenticMemoryContextPackingStatus,
	type AgenticMemoryContextState,
	type AgenticMemoryContextText,
	type AgenticMemoryContextTruncation,
	type AgenticMemoryDurabilityDownstreamAdvance,
	type AgenticMemoryDurabilityDownstreamAdvancePolicy,
	type AgenticMemoryDurabilityGateAuditEntry,
	type AgenticMemoryDurabilityGateBundle,
	type AgenticMemoryDurabilityGateBundleOptions,
	type AgenticMemoryDurabilityGateCursor,
	type AgenticMemoryDurabilityGateInput,
	type AgenticMemoryDurabilityGateProjection,
	type AgenticMemoryDurabilityGateStatus,
	type AgenticMemoryDurabilityGateStatusState,
	type AgenticMemoryDurabilityResult,
	type AgenticMemoryDurabilityUncertainResolutionStatus,
	type AgenticMemoryError,
	type AgenticMemoryErrorCode,
	type AgenticMemoryFactCommitResult,
	type AgenticMemoryFactCommitStatus,
	type AgenticMemoryFactLogAuditEntry,
	type AgenticMemoryFactRef,
	type AgenticMemoryFragmentFrame,
	type AgenticMemoryKgAssertionDraft,
	type AgenticMemoryKgProjectionBundle,
	type AgenticMemoryKgProjectionBundleOptions,
	type AgenticMemoryKgProjectionCursor,
	type AgenticMemoryKgProjectionError,
	type AgenticMemoryKgProjectionErrorCode,
	type AgenticMemoryKgProjectionSnapshot,
	type AgenticMemoryKgProjectionStatus,
	type AgenticMemoryKgProjectionStatusState,
	type AgenticMemoryKind,
	type AgenticMemoryMaterializedFactLogBootstrapAuditEntry,
	type AgenticMemoryMaterializedFactLogBootstrapBundle,
	type AgenticMemoryMaterializedFactLogBootstrapBundleOptions,
	type AgenticMemoryMaterializedFactLogBootstrapCursor,
	type AgenticMemoryMaterializedFactLogBootstrapInput,
	type AgenticMemoryMaterializedFactLogBootstrapProjection,
	type AgenticMemoryMaterializedFactLogBootstrapStatus,
	type AgenticMemoryMaterializedFactLogBootstrapStatusState,
	type AgenticMemoryPackedContext,
	type AgenticMemoryPackedContextEntry,
	type AgenticMemoryPersistenceLevel,
	type AgenticMemoryProjectionCursor,
	type AgenticMemoryProjectionSnapshot,
	type AgenticMemoryProposalAdmissionAudit,
	type AgenticMemoryProposalAdmissionCursor,
	type AgenticMemoryProposalAdmissionDecision,
	type AgenticMemoryProposalAdmissionDecisionState,
	type AgenticMemoryProposalAdmissionIssue,
	type AgenticMemoryProposalAdmissionOptions,
	type AgenticMemoryProposalAdmissionPolicy,
	type AgenticMemoryProposalAdmissionSnapshot,
	type AgenticMemoryProposalAdmissionStatus,
	type AgenticMemoryProposalAdmissionStatusState,
	type AgenticMemoryRecord,
	type AgenticMemoryRecordAdmission,
	type AgenticMemoryRecordAdmissionAuditEntry,
	type AgenticMemoryRecordAdmissionBundle,
	type AgenticMemoryRecordAdmissionBundleOptions,
	type AgenticMemoryRecordAdmissionCursor,
	type AgenticMemoryRecordAdmissionDecisionState,
	type AgenticMemoryRecordAdmissionPolicy,
	type AgenticMemoryRecordAdmissionPolicyCandidate,
	type AgenticMemoryRecordAdmissionPolicyMaterial,
	type AgenticMemoryRecordAdmissionPolicySelectionInput,
	type AgenticMemoryRecordAdmissionPolicySource,
	type AgenticMemoryRecordAdmissionPolicySourceAuditEntry,
	type AgenticMemoryRecordAdmissionPolicySourceBundle,
	type AgenticMemoryRecordAdmissionPolicySourceBundleOptions,
	type AgenticMemoryRecordAdmissionPolicySourceCursor,
	type AgenticMemoryRecordAdmissionPolicySourceKind,
	type AgenticMemoryRecordAdmissionPolicySourceProjection,
	type AgenticMemoryRecordAdmissionPolicySourceStatus,
	type AgenticMemoryRecordAdmissionPolicySourceStatusState,
	type AgenticMemoryRecordAdmissionSnapshot,
	type AgenticMemoryRecordAdmissionStatus,
	type AgenticMemoryRecordAdmissionStatusState,
	type AgenticMemoryRecordApplicationAuditEntry,
	type AgenticMemoryRecordApplicationBundle,
	type AgenticMemoryRecordApplicationBundleOptions,
	type AgenticMemoryRecordApplicationCursor,
	type AgenticMemoryRecordApplicationDecision,
	type AgenticMemoryRecordApplicationDecisionState,
	type AgenticMemoryRecordApplicationEvidence,
	type AgenticMemoryRecordApplicationEvidenceFactsBundle,
	type AgenticMemoryRecordApplicationEvidenceFactsBundleOptions,
	type AgenticMemoryRecordApplicationEvidenceFactsProjection,
	type AgenticMemoryRecordApplicationEvidenceProjectionAuditEntry,
	type AgenticMemoryRecordApplicationEvidenceProjectionStatus,
	type AgenticMemoryRecordApplicationEvidenceProjectionStatusState,
	type AgenticMemoryRecordApplicationMaterialFrame,
	type AgenticMemoryRecordApplicationMaterialIdentity,
	type AgenticMemoryRecordApplicationMaterialIdentityAlgorithm,
	type AgenticMemoryRecordApplicationOperation,
	type AgenticMemoryRecordApplicationOperationCursor,
	type AgenticMemoryRecordApplicationOperationStatus,
	type AgenticMemoryRecordApplicationOptions,
	type AgenticMemoryRecordApplicationPolicy,
	type AgenticMemoryRecordApplicationPriorEvidence,
	type AgenticMemoryRecordApplicationPriorEvidenceBundle,
	type AgenticMemoryRecordApplicationPriorEvidenceBundleOptions,
	type AgenticMemoryRecordApplicationPriorEvidenceCursor,
	type AgenticMemoryRecordApplicationPriorEvidenceProjection,
	type AgenticMemoryRecordApplicationReasonCode,
	type AgenticMemoryRecordApplicationSnapshot,
	type AgenticMemoryRecordApplicationStatus,
	type AgenticMemoryRecordApplicationStatusState,
	type AgenticMemoryRecordCandidateMaterial,
	type AgenticMemoryRecordFrame,
	type AgenticMemoryRecordMaterializationAuditEntry,
	type AgenticMemoryRecordMaterializationCursor,
	type AgenticMemoryRecordMaterializationIntent,
	type AgenticMemoryRecordMaterializationProjection,
	type AgenticMemoryRecordMaterializationStatus,
	type AgenticMemoryRecordMaterializationStatusState,
	type AgenticMemoryRecordMaterializerBundle,
	type AgenticMemoryRecordMaterializerBundleOptions,
	type AgenticMemoryRecordMetadata,
	type AgenticMemoryRecordProposal,
	type AgenticMemoryRecordStoreFrame,
	type AgenticMemoryRecordStoreFrameAudit,
	type AgenticMemoryRecordStoreFrameBundle,
	type AgenticMemoryRecordStoreFrameBundleOptions,
	type AgenticMemoryRecordStoreFrameCursor,
	type AgenticMemoryRecordStoreFrameProjection,
	type AgenticMemoryRecordStoreFrameStatus,
	type AgenticMemoryRecordStoreFrameStatusState,
	type AgenticMemoryRetentionBundle,
	type AgenticMemoryRetentionBundleOptions,
	type AgenticMemoryRetentionCommand,
	type AgenticMemoryRetentionCursor,
	type AgenticMemoryRetentionError,
	type AgenticMemoryRetentionErrorCode,
	type AgenticMemoryRetentionSnapshot,
	type AgenticMemoryRetentionStatus,
	type AgenticMemoryScope,
	type AgenticMemorySourceProjection,
	type AgenticMemoryStatus,
	type AgenticMemoryStatusState,
	type AgenticMemoryStrictJsonValue,
	type AgenticWorkItemMemoryApplicationRecipeBundle,
	type AgenticWorkItemMemoryApplicationRecipeBundleOptions,
	type AgenticWorkItemMemoryApplicationRecipeInput,
	type AgenticWorkItemMemoryApplicationRecipeResult,
	type AgenticWorkItemMemoryBridgeAuditEntry,
	type AgenticWorkItemMemoryBridgeBundle,
	type AgenticWorkItemMemoryBridgeBundleOptions,
	type AgenticWorkItemMemoryBridgeCursor,
	type AgenticWorkItemMemoryBridgeInput,
	type AgenticWorkItemMemoryBridgeIssue,
	type AgenticWorkItemMemoryBridgeResult,
	type AgenticWorkItemMemoryBridgeStatus,
	type AgenticWorkItemMemoryBridgeStatusState,
	type AgenticWorkItemMemoryContextFact,
	type AgenticWorkItemMemoryDataSelector,
	type AgenticWorkItemMemoryFieldPath,
	type AgenticWorkItemMemoryInputLane,
	type AgenticWorkItemMemoryMappingPolicy,
	type AgenticWorkItemMemoryRecordCandidate,
	type AgenticWorkItemMemoryRecordMappingRule,
	type AgenticWorkItemMemoryScoreMappingRule,
	admitAgenticMemoryRecordProposals,
	agenticMemoryApplicationDecisionStoreFrameCodec,
	agenticMemoryApplicationEvidenceStoreFrameBundle,
	agenticMemoryApplicationEvidenceStoreFrameCodec,
	agenticMemoryBundle,
	agenticMemoryCommittedApplicationDecisionFact,
	agenticMemoryCommittedApplicationEvidenceFact,
	agenticMemoryCommittedFact,
	agenticMemoryCommittedFactBatch,
	agenticMemoryCommittedFactBatchCodec,
	agenticMemoryCommittedFactIdentity,
	agenticMemoryCommittedFactLogAppendAttempt,
	agenticMemoryCommittedFactLogBackendAdapter,
	agenticMemoryCommittedFactLogBackendCursor,
	agenticMemoryCommittedFactLogBackendStatus,
	agenticMemoryCommittedFactLogStartupRead,
	agenticMemoryCommittedFactMaterialIdentity,
	agenticMemoryCommittedFactReadMaterializationBundle,
	agenticMemoryCommittedFactSnapshot,
	agenticMemoryCommittedFactSnapshotTailEquivalent,
	agenticMemoryCommittedPriorEvidenceFact,
	agenticMemoryCommittedRecordMaterialFact,
	agenticMemoryConsolidationApplicationBundle,
	agenticMemoryConsolidationBundle,
	agenticMemoryContextPackingBundle,
	agenticMemoryDurabilityAdvanceOnCommittedOrDuplicatePolicy,
	agenticMemoryDurabilityGateBundle,
	agenticMemoryDurabilityGateInput,
	agenticMemoryDurabilityResultMayAdvance,
	agenticMemoryDurabilityUncertainResolutionStatus,
	agenticMemoryFactCommitStatusIsDurable,
	agenticMemoryFactCommitStatusIsTerminalFailure,
	agenticMemoryKgProjectionBundle,
	agenticMemoryMaterializedFactLogBootstrapBundle,
	agenticMemoryMaterializedFactLogBootstrapInput,
	agenticMemoryRecordAdmissionBundle,
	agenticMemoryRecordAdmissionPolicySourceBundle,
	agenticMemoryRecordApplicationBundle,
	agenticMemoryRecordApplicationEvidenceFactsBundle,
	agenticMemoryRecordApplicationPriorEvidenceBundle,
	agenticMemoryRecordCodec,
	agenticMemoryRecordFrame,
	agenticMemoryRecordFrameCodec,
	agenticMemoryRecordMaterializerBundle,
	agenticMemoryRecordStoreFrameBundle,
	agenticMemoryRecordStoreFrameCodec,
	agenticMemoryRetentionBundle,
	agenticWorkItemMemoryApplicationRecipeBundle,
	agenticWorkItemMemoryBridgeBundle,
	applyAgenticMemoryRecordAdmissions,
	assertAgenticMemoryCommittedFact,
	assertAgenticMemoryCommittedFactBatch,
	assertAgenticMemoryRecordFrame,
	decodeAgenticMemoryApplicationDecisionStoreFrame,
	decodeAgenticMemoryApplicationEvidenceStoreFrame,
	decodeAgenticMemoryRecordStoreFrame,
	frameAgenticMemoryApplicationDecisions,
	frameAgenticMemoryApplicationEvidence,
	frameAgenticMemoryRecords,
	type KnowledgeAssertion,
	type KnowledgeAssertionObject,
	type KnowledgeAssertionSubject,
	mapAgenticWorkItemMemoryApplicationRecipe,
	mapAgenticWorkItemMemoryBridge,
	materializeAgenticMemoryCommittedFactSnapshotTail,
	materializeAgenticMemoryCommittedFacts,
	materializeAgenticMemoryRecordChanges,
	memoryAgenticMemoryCommittedFactLog,
	normalizeAgenticMemoryCommittedFactLogBackendAppendResult,
	normalizeAgenticMemoryCommittedFactLogBackendReadResult,
	projectAgenticMemoryCommittedFactReadMaterialization,
	projectAgenticMemoryDurabilityGate,
	projectAgenticMemoryMaterializedFactLogBootstrap,
	projectAgenticMemoryRecordAdmissionPolicySource,
	projectAgenticMemoryRecordApplicationEvidenceFacts,
	projectAgenticMemoryRecordApplicationPriorEvidence,
} from "./solutions/index.js";
export {
	APPEND_LOG_SEQ_PAD,
	type AppendLogEntry,
	type AppendLogPage,
	type AppendLogReadOptions,
	type AppendLogStorageTier,
	appendLogKey,
	appendLogStorage,
	assertChangeEnvelope,
	assertDecimalIntegerString,
	assertNonNegativeDecimalIntegerString,
	assertObserveEventFrame,
	assertReactiveCollectionChangeFrame,
	assertReactiveCollectionSnapshotFrame,
	assertWalFrame,
	bigIntToDecimalString,
	bigIntToNonNegativeDecimalString,
	type ChangeEnvelope,
	type ChangeEnvelopeOptions,
	type ChangeLifecycle,
	type Codec,
	type ContentAddressedKv,
	type ContentAddressedKvOptions,
	ContentAddressedMissError,
	type ContentAddressedMode,
	type ContentAddressedStorage,
	type ContentAddressedStorageOptions,
	changeEnvelopeCodec,
	collectionSnapshotKey,
	contentAddressedKv,
	contentAddressedStorage,
	type DecimalIntegerString,
	decimalStringToBigInt,
	dictKv,
	envelopeChange,
	hasKvPutIfAbsent,
	hasKvVersioned,
	hasStoragePutIfAbsent,
	hasStorageVersioned,
	isDecimalIntegerString,
	isNonNegativeDecimalIntegerString,
	jsonCodec,
	jsonCodecFor,
	type KvGeneration,
	type KvStorageOptions,
	type KvStorageTier,
	type KvVersionedRead,
	kvStorage,
	type LoadReactiveCollectionStateOptions,
	listByPrefix,
	loadReactiveIndexState,
	loadReactiveListState,
	loadReactiveLogState,
	loadReactiveMapState,
	type MemoryBackend,
	type MultiWriterAppendLogOptions,
	type MultiWriterAppendLogStorageTier,
	memoryAppendLog,
	memoryBackend,
	memoryKv,
	memoryMultiWriterAppendLog,
	multiWriterAppendLogStorage,
	type NonNegativeDecimalIntegerString,
	nonNegativeDecimalStringToBigInt,
	nowNs,
	type ObserveEventFrame,
	type ObserveEventLogPage,
	observeEventFrame,
	observeEventFrameCodec,
	type PutIfAbsentKvStorageTier,
	type PutIfAbsentStorageBackend,
	REACTIVE_COLLECTION_CHANGE_FORMAT,
	REACTIVE_COLLECTION_FRAME_VERSION,
	REACTIVE_COLLECTION_SNAPSHOT_FORMAT,
	type ReactiveCollectionChangeFrame,
	type ReactiveCollectionRestoreState,
	type ReactiveCollectionSnapshotFrame,
	type ReactiveCollectionStorageKind,
	type ReactiveIndexRestoreState,
	type ReactiveListRestoreState,
	type ReactiveLogRestoreState,
	type ReactiveMapRestoreState,
	type ReadThroughErrorContext,
	type ReadThroughLookupFact,
	type ReadThroughLookupTier,
	type ReadThroughMissContext,
	type ReadThroughPromotionFact,
	reactiveCollectionChangeFrame,
	reactiveCollectionChangeFrameCodec,
	reactiveCollectionSnapshotFrame,
	reactiveCollectionSnapshotFrameCodec,
	readAppendLogPage,
	readObserveEventLogPage,
	readThroughKv,
	requireKvPutIfAbsent,
	requireKvVersioned,
	requireStoragePutIfAbsent,
	requireStorageVersioned,
	type StorageBackend,
	type StorageGeneration,
	type StorageNamespaceOptions,
	type StorageTimestampNs,
	type StorageVersionedRead,
	stableJsonString,
	strictJsonCodec,
	strictJsonCodecFor,
	type TieredReadThroughOptions,
	type TieredReadThroughResult,
	tieredReadThrough,
	type VersionedKvStorageTier,
	type VersionedStorageBackend,
	verifyWalFrameChecksum,
	WAL_FORMAT_VERSION,
	WAL_FRAME_SEQ_PAD,
	WAL_KEY_SEGMENT,
	type WalFrame,
	type WalFrameBody,
	type WalFrameOptions,
	type WalFrameTimestampNs,
	type WebStorageLike,
	walFrame,
	walFrameChecksum,
	walFrameCodec,
	walFrameKey,
	walFramePrefix,
	webStorageBackend,
} from "./storage/index.js";
export {
	assertDirtyPrecedesTerminalData,
	type MessageSequence,
} from "./testing/index.js";
