/**
 * @graphrefly/ts — clean-slate TypeScript package.
 *
 * Canonical authority: ~/src/graphrefly/spec/rules.jsonl + decisions.jsonl.
 * CSP-1 substrate: node / dispatcher / pool / wave protocol.
 * CSP-2 graph layer: Graph + 8-verb sugar + describe/observe/profile inspection.
 */

export { type BatchCtx, batch } from "./batch/batch.js";
export type {
	Ctx,
	CtxState,
	NodeFn,
	RewireNext,
	Sink,
	TerminalData,
	WaveData,
} from "./ctx/types.js";
export {
	depBatch,
	depCount,
	depLatest,
	depTerminal,
	depWaves,
	isTerminalComplete,
	isTerminalError,
	isTerminalNone,
	terminalErrorValue,
} from "./ctx/types.js";
export {
	Dispatcher,
	defaultDispatcher,
	type Handle,
	type HandleStat,
	type Pool,
	type PoolKind,
} from "./dispatcher/index.js";
export {
	type CascadingCacheEvent,
	type CascadingCachePolicy,
	type CascadingCacheStatus,
	type ReactiveCascadingCache,
	type ReactiveCascadingCacheOptions,
	reactiveCascadingCache,
} from "./graph/cascading-cache.js";
export {
	GRAPH_CHECKPOINT_VERSION,
	type GraphCheckpoint,
	type GraphCheckpointEdge,
	type GraphCheckpointFactory,
	type GraphCheckpointJson,
	type GraphCheckpointMount,
	type GraphCheckpointNode,
	type GraphCheckpointTerminal,
	type GraphCheckpointValue,
	type GraphCheckpointVersion,
} from "./graph/checkpoint.js";
export {
	buffer,
	bufferCount,
	combine,
	combineLatest,
	concat,
	race,
	sample,
	takeUntil,
	withLatestFrom,
	zip,
} from "./graph/combinators.js";
export {
	type DescribeChangeset,
	type DescribeEvent,
	type PipeOperator,
	pipe,
	type Stratified,
	type StratifyOptions,
	type StratifyRule,
	stratify,
	stratifyBranch,
	topologyDiff,
} from "./graph/composition.js";
export type {
	IndexChange,
	ListChange,
	LogChange,
	MapChange,
} from "./graph/data-structures/change.js";
export {
	type IndexRow,
	type ReactiveIndex,
	type ReactiveIndexCapacityOrder,
	type ReactiveIndexCapacityPolicy,
	type ReactiveIndexOpt,
	type ReactiveIndexOptions,
	reactiveIndex,
} from "./graph/data-structures/reactive-index.js";
export {
	type ReactiveList,
	type ReactiveListOpt,
	type ReactiveListOptions,
	reactiveList,
} from "./graph/data-structures/reactive-list.js";
export {
	mergeReactiveLogs,
	type ReactiveLog,
	type ReactiveLogOptions,
	reactiveLog,
	scanLog,
} from "./graph/data-structures/reactive-log.js";
export {
	type ReactiveMap,
	type ReactiveMapOpt,
	type ReactiveMapOptions,
	type ReactiveMapRetentionEntry,
	type ReactiveMapRetentionPolicy,
	reactiveMap,
} from "./graph/data-structures/reactive-map.js";
export type {
	DescribeEdge,
	DescribeNode,
	DescribeOpts,
	DescribeSnapshot,
} from "./graph/describe.js";
export {
	type CausalChain,
	type CausalStep,
	type ExplainPathOptions,
	type ExplainPathReason,
	explainPath,
	type IslandReport,
	type ReachableDirection,
	type ReachableOptions,
	type ReachableResult,
	reachable,
	type ValidateNoIslandsResult,
	validateNoIslands,
} from "./graph/diagnostics.js";
export {
	type DerivedFn,
	type EffectFn,
	Graph,
	type GraphOptions,
	graph,
	StateNode,
	type SugarOpts,
} from "./graph/graph.js";
export {
	concatMap,
	exhaustMap,
	flatMap,
	type MergeMapOptions,
	mergeMap,
	type Project,
	repeat,
	switchMap,
} from "./graph/higher-order.js";
export type { NodeProfile, ObserveEvent, ObserveStream, Profile } from "./graph/inspect.js";
export {
	catchError,
	type DefineOpts,
	type Definition,
	define,
	distinctUntilChanged,
	elementAt,
	filter,
	find,
	first,
	initNode,
	last,
	map,
	merge,
	type Operator,
	onFirstData,
	pairwise,
	type RestoreRegistryEntry,
	reduce,
	rescue,
	restoreRegistry,
	type SettleOpts,
	scan,
	settle,
	skip,
	type TapObserver,
	take,
	takeWhile,
	tap,
	tapFirst,
	type ValveOpts,
	valve,
} from "./graph/operators.js";
export type {
	CapacityPolicy,
	OrderedCapacityPolicy,
	ReactiveOpt,
	RetentionPolicy,
	ViewCachePolicy,
} from "./graph/policies/types.js";
export {
	type DescribeToAsciiOptions,
	type DescribeToD2Options,
	type DescribeToJsonOptions,
	type DescribeToMermaidOptions,
	type DescribeToMermaidUrlOptions,
	type DescribeToPrettyOptions,
	type DiagramDirection,
	describeToAscii,
	describeToD2,
	describeToJson,
	describeToMermaid,
	describeToMermaidUrl,
	describeToPretty,
	type MermaidLiveTheme,
	type MermaidLiveUrlOptions,
	mermaidLiveUrl,
} from "./graph/render.js";
export {
	defaultRestoreRegistry,
	type GraphRestoreDefinition,
	type GraphRestoreDescriptor,
	type GraphRestoreDescriptorContext,
	type GraphRestoreEntry,
	type GraphRestoreRegistry,
	mapRestoreDescriptor,
	type RestoreGraphOptions,
	restoreGraph,
	stateRestoreDescriptor,
	takeRestoreDescriptor,
	timerRestoreDescriptor,
} from "./graph/restore.js";
export {
	type AsyncSourceOpts,
	type EventListenerOptionsLike,
	type EventTargetLike,
	empty,
	type FromEventOptions,
	firstValueFrom,
	fromAny,
	fromAsyncIter,
	fromEvent,
	fromIter,
	fromPromise,
	fromPushNotification,
	fromTimer,
	interval,
	type NodeInput,
	never,
	of,
	type PushRegister,
	type PushUnsubscribe,
	type SingleFromAnyOptions,
	singleFromAny,
	type TimerSourceOpts,
	throwError,
	timer,
} from "./graph/sources.js";
export {
	audit,
	auditTime,
	bufferTime,
	debounce,
	debounceTime,
	delay,
	throttle,
	throttleTime,
	timeout,
} from "./graph/time.js";
export { strictCanonicalJsonBytes } from "./json/codec.js";
export { dynamicNode, Node, type NodeOptions, node, type Status } from "./node/node.js";
export {
	defaultNodeVersionHash,
	type NodeVersion,
	type NodeVersionHashFn,
	type NodeVersioningLevel,
	type NodeVersioningPolicy,
	type NodeVersionJson,
	type NodeVersionV0,
	type NodeVersionV1,
} from "./node/versioning.js";
export * from "./protocol/messages.js";
export {
	APPEND_LOG_SEQ_PAD,
	type AppendLogEntry,
	type AppendLogPage,
	type AppendLogReadOptions,
	type AppendLogStorageTier,
	type AttachObserveEventLogOptions,
	type AttachObserveSinkOptions,
	appendLogKey,
	appendLogStorage,
	assertChangeEnvelope,
	assertDecimalIntegerString,
	assertNonNegativeDecimalIntegerString,
	assertObserveEventFrame,
	assertWalFrame,
	attachObserveEventLog,
	attachObserveSink,
	bigIntToDecimalString,
	bigIntToNonNegativeDecimalString,
	type ChangeEnvelope,
	type ChangeEnvelopeOptions,
	type ChangeLifecycle,
	type Codec,
	type ContentAddressedKv,
	type ContentAddressedKvOptions,
	ContentAddressedMissError,
	type ContentAddressedMode,
	type ContentAddressedStorage,
	type ContentAddressedStorageOptions,
	changeEnvelopeCodec,
	contentAddressedKv,
	contentAddressedStorage,
	type DecimalIntegerString,
	decimalStringToBigInt,
	dictKv,
	envelopeChange,
	hasKvPutIfAbsent,
	hasKvVersioned,
	hasStoragePutIfAbsent,
	hasStorageVersioned,
	isDecimalIntegerString,
	isNonNegativeDecimalIntegerString,
	jsonCodec,
	jsonCodecFor,
	type KvGeneration,
	type KvStorageOptions,
	type KvStorageTier,
	type KvVersionedRead,
	kvStorage,
	listByPrefix,
	type MemoryBackend,
	type MultiWriterAppendLogOptions,
	type MultiWriterAppendLogStorageTier,
	memoryAppendLog,
	memoryBackend,
	memoryKv,
	memoryMultiWriterAppendLog,
	multiWriterAppendLogStorage,
	type NonNegativeDecimalIntegerString,
	nonNegativeDecimalStringToBigInt,
	nowNs,
	type ObserveEventFrame,
	type ObserveEventLogHandle,
	type ObserveEventLogPage,
	type ObserveSink,
	type ObserveSinkDone,
	type ObserveSinkErrorContext,
	type ObserveSinkHandle,
	observeEventFrame,
	observeEventFrameCodec,
	type PutIfAbsentKvStorageTier,
	type PutIfAbsentStorageBackend,
	type ReadThroughErrorContext,
	type ReadThroughLookupFact,
	type ReadThroughLookupTier,
	type ReadThroughMissContext,
	type ReadThroughPromotionFact,
	readAppendLogPage,
	readObserveEventLogPage,
	readThroughKv,
	requireKvPutIfAbsent,
	requireKvVersioned,
	requireStoragePutIfAbsent,
	requireStorageVersioned,
	type StorageBackend,
	type StorageGeneration,
	type StorageNamespaceOptions,
	type StorageTimestampNs,
	type StorageVersionedRead,
	stableJsonString,
	strictJsonCodec,
	strictJsonCodecFor,
	type TieredReadThroughOptions,
	type TieredReadThroughResult,
	tieredReadThrough,
	type VersionedKvStorageTier,
	type VersionedStorageBackend,
	verifyWalFrameChecksum,
	WAL_FORMAT_VERSION,
	WAL_FRAME_SEQ_PAD,
	WAL_KEY_SEGMENT,
	type WalFrame,
	type WalFrameBody,
	type WalFrameOptions,
	type WalFrameTimestampNs,
	type WebStorageLike,
	walFrame,
	walFrameChecksum,
	walFrameCodec,
	walFrameKey,
	walFramePrefix,
	webStorageBackend,
} from "./storage/index.js";
export {
	assertDirtyPrecedesTerminalData,
	type MessageSequence,
} from "./testing/index.js";
