/**
 * Graph container: registry, wiring, introspection (Phase 1).
 */

export { OVERHEAD as SIZEOF_OVERHEAD, SIZEOF_SYMBOL, sizeof } from "../core/_internal/sizeof.js";
export type {
	GraphChange,
	GraphChangeBatchEnd,
	GraphChangeBatchStart,
	GraphChangeComplete,
	GraphChangeData,
	GraphChangeDirty,
	GraphChangeEnvelope,
	GraphChangeError,
	GraphChangeInvalidate,
	GraphChangeMount,
	GraphChangeNodeAdded,
	GraphChangeNodeRemoved,
	GraphChangePause,
	GraphChangeReserved,
	GraphChangeResolved,
	GraphChangeResubscribe,
	GraphChangeResume,
	GraphChangeSnapshot,
	GraphChangeTeardown,
	GraphChangeTrace,
	GraphChangeType,
	GraphChangeUnmount,
} from "./changeset.js";
export {
	createDagCborCodec,
	createDagCborZstdCodec,
	decodeEnvelope,
	ENVELOPE_VERSION,
	type EvictedSubgraphInfo,
	type EvictionPolicy,
	encodeEnvelope,
	type GraphCodec,
	JsonCodec,
	type LazyGraphCodec,
	registerBuiltinCodecs,
	replayWAL,
	type WALEntry,
} from "./codec.js";
export {
	type CausalChain,
	type CausalStep,
	type ExplainPathOptions,
	explainPath,
} from "./explain.js";
export {
	type DescribeFilter,
	diffForWAL,
	type FnCtxDerived,
	type FnCtxEffect,
	type FnCtxProducer,
	GRAPH_META_SEGMENT,
	Graph,
	type GraphActorOptions,
	type GraphAttachStorageOptions,
	type GraphCheckpointRecord,
	type GraphDerivedFn,
	type GraphDerivedOptions,
	type GraphDescribeOptions,
	type GraphDescribeOutput,
	type GraphDiagramDirection,
	type GraphDiffChange,
	type GraphDiffResult,
	type GraphEffectFn,
	type GraphEffectOptions,
	type GraphFactoryContext,
	type GraphNodeFactory,
	type GraphObserveAll,
	type GraphObserveOne,
	type GraphOptions,
	type GraphPersistSnapshot,
	type GraphProducerOptions,
	type GraphProducerSetupFn,
	type GraphStateOptions,
	type GraphVersionChange,
	type GraphWALDiff,
	type NodeUpActions,
	type ObserveChangeset,
	type ObserveDetail,
	type ObserveEvent,
	type ObserveOptions,
	type ObserveResult,
	type ObserveTheme,
	type ObserveThemeName,
	type ObserveTier,
	type ReachableDirection,
	type ReachableOptions,
	reachable,
	SNAPSHOT_VERSION,
	type TopologyEvent,
	type TraceEntry,
} from "./graph.js";
export {
	type GraphProfileOptions,
	type GraphProfileResult,
	graphProfile,
	type NodeProfile,
} from "./profile.js";
export { watchTopologyTree } from "./topology-tree.js";
export {
	type IslandReport,
	type ValidateNoIslandsResult,
	validateNoIslands,
} from "./validate-no-islands.js";
// validateGraphObservability moved to root src/base/validate-observability.ts (cleave A2)
// It depends on render (presentation layer) so it cannot live in the substrate.
