/**
 * Vertical application solution kits.
 *
 * Agentic memory, harness, and data-agent surfaces land here after B63/B62
 * classify and re-derive them onto lower D125 layers.
 */

export {
	AGENTIC_MEMORY_RECORD_FRAME_FORMAT,
	AGENTIC_MEMORY_RECORD_FRAME_VERSION,
	type AgenticMemoryArtifactKind,
	type AgenticMemoryBundle,
	type AgenticMemoryBundleOptions,
	type AgenticMemoryConsolidationBundle,
	type AgenticMemoryConsolidationBundleOptions,
	type AgenticMemoryConsolidationCommand,
	type AgenticMemoryConsolidationCursor,
	type AgenticMemoryConsolidationError,
	type AgenticMemoryConsolidationErrorCode,
	type AgenticMemoryConsolidationOutcome,
	type AgenticMemoryConsolidationRecordDraft,
	type AgenticMemoryConsolidationRequest,
	type AgenticMemoryConsolidationResult,
	type AgenticMemoryConsolidationSnapshot,
	type AgenticMemoryConsolidationStatus,
	type AgenticMemoryContext,
	type AgenticMemoryContextEntry,
	type AgenticMemoryContextPackingBundle,
	type AgenticMemoryContextPackingBundleOptions,
	type AgenticMemoryContextPackingCursor,
	type AgenticMemoryContextPackingError,
	type AgenticMemoryContextPackingErrorCode,
	type AgenticMemoryContextPackingPolicy,
	type AgenticMemoryContextPackingSnapshot,
	type AgenticMemoryContextPackingStatus,
	type AgenticMemoryContextState,
	type AgenticMemoryContextText,
	type AgenticMemoryError,
	type AgenticMemoryErrorCode,
	type AgenticMemoryFragmentFrame,
	type AgenticMemoryKgAssertionDraft,
	type AgenticMemoryKgProjectionBundle,
	type AgenticMemoryKgProjectionBundleOptions,
	type AgenticMemoryKgProjectionCursor,
	type AgenticMemoryKgProjectionError,
	type AgenticMemoryKgProjectionErrorCode,
	type AgenticMemoryKgProjectionSnapshot,
	type AgenticMemoryKgProjectionStatus,
	type AgenticMemoryKgProjectionStatusState,
	type AgenticMemoryKind,
	type AgenticMemoryPackedContext,
	type AgenticMemoryPackedContextEntry,
	type AgenticMemoryPersistenceLevel,
	type AgenticMemoryProjectionCursor,
	type AgenticMemoryProjectionSnapshot,
	type AgenticMemoryRecord,
	type AgenticMemoryRecordFrame,
	type AgenticMemoryRecordMetadata,
	type AgenticMemoryRetentionBundle,
	type AgenticMemoryRetentionBundleOptions,
	type AgenticMemoryRetentionCommand,
	type AgenticMemoryRetentionCursor,
	type AgenticMemoryRetentionError,
	type AgenticMemoryRetentionErrorCode,
	type AgenticMemoryRetentionSnapshot,
	type AgenticMemoryRetentionStatus,
	type AgenticMemoryScope,
	type AgenticMemorySourceProjection,
	type AgenticMemoryStatus,
	type AgenticMemoryStatusState,
	type AgenticMemoryStrictJsonValue,
	agenticMemoryBundle,
	agenticMemoryConsolidationBundle,
	agenticMemoryContextPackingBundle,
	agenticMemoryKgProjectionBundle,
	agenticMemoryRecordCodec,
	agenticMemoryRecordFrame,
	agenticMemoryRecordFrameCodec,
	agenticMemoryRetentionBundle,
	assertAgenticMemoryRecordFrame,
	type KnowledgeAssertion,
	type KnowledgeAssertionObject,
	type KnowledgeAssertionSubject,
} from "./agentic-memory.js";

export {
	analyzeAndMeasure,
	type BaseContentBlock,
	type BlockAdapters,
	CellMeasureAdapter,
	type CellMeasureAdapterOptions,
	type CircleObstacle,
	type ComputeFlowLinesOptions,
	type ContentBlock,
	carveTextLineSlots,
	circleIntervalForBand,
	computeBlockFlow,
	computeCharPositions,
	computeFlowLines,
	computeLineBreaks,
	computeTotalHeight,
	type FlowColumns,
	type FlowContainer,
	type FlowLinesResult,
	type ImageContentBlock,
	type ImageMeasurer,
	ImageSizeAdapter,
	InjectedMeasureAdapter,
	type InjectedMeasureAdapterOptions,
	type LayoutCursor,
	type LayoutLine,
	type LayoutNextLineContext,
	type LayoutNextLineResult,
	type LineBreaksResult,
	layoutNextLine,
	type MeasureBlockOptions,
	type MeasuredBlock,
	type MeasureFn,
	type MeasurementAdapter,
	measureBlock,
	measureBlocks,
	type Obstacle,
	type PositionedBlock,
	type PositionedLine,
	PrecomputedMeasureAdapter,
	type PrecomputedMeasureAdapterOptions,
	type PreparedSegment,
	type ReactiveBlockLayoutBundle,
	type ReactiveBlockLayoutOptions,
	type ReactiveFlowLayoutBundle,
	type ReactiveFlowLayoutOptions,
	type ReactiveLayoutBundle,
	type ReactiveLayoutOptions,
	type RectObstacle,
	reactiveBlockLayout,
	reactiveFlowLayout,
	reactiveLayout,
	rectIntervalForBand,
	type SegmentAdapter,
	type SegmentBreakKind,
	type SegmentInfo,
	type SegmentMeasureStats,
	type Size,
	SvgBoundsAdapter,
	type SvgContentBlock,
	type SvgMeasurer,
	type TextContentBlock,
} from "./reactive-layout/index.js";
