/**
 * Vertical application solution kits.
 *
 * Agentic memory, harness, and data-agent surfaces land here after B63/B62
 * classify and re-derive them onto lower D125 layers.
 */

export {
	AGENTIC_MEMORY_RECORD_APPLICATION_MATERIAL_IDENTITY_ALGORITHM,
	AGENTIC_MEMORY_RECORD_FRAME_FORMAT,
	AGENTIC_MEMORY_RECORD_FRAME_VERSION,
	type AgenticMemoryArtifactKind,
	type AgenticMemoryBundle,
	type AgenticMemoryBundleOptions,
	type AgenticMemoryConsolidationApplicationBundle,
	type AgenticMemoryConsolidationApplicationBundleOptions,
	type AgenticMemoryConsolidationBundle,
	type AgenticMemoryConsolidationBundleOptions,
	type AgenticMemoryConsolidationCommand,
	type AgenticMemoryConsolidationCursor,
	type AgenticMemoryConsolidationError,
	type AgenticMemoryConsolidationErrorCode,
	type AgenticMemoryConsolidationOutcome,
	type AgenticMemoryConsolidationRecordDraft,
	type AgenticMemoryConsolidationRequest,
	type AgenticMemoryConsolidationResult,
	type AgenticMemoryConsolidationSnapshot,
	type AgenticMemoryConsolidationStatus,
	type AgenticMemoryContext,
	type AgenticMemoryContextAttribution,
	type AgenticMemoryContextEntry,
	type AgenticMemoryContextPackingBundle,
	type AgenticMemoryContextPackingBundleOptions,
	type AgenticMemoryContextPackingCursor,
	type AgenticMemoryContextPackingError,
	type AgenticMemoryContextPackingErrorCode,
	type AgenticMemoryContextPackingPolicy,
	type AgenticMemoryContextPackingSnapshot,
	type AgenticMemoryContextPackingStatus,
	type AgenticMemoryContextState,
	type AgenticMemoryContextText,
	type AgenticMemoryContextTruncation,
	type AgenticMemoryError,
	type AgenticMemoryErrorCode,
	type AgenticMemoryFactRef,
	type AgenticMemoryFragmentFrame,
	type AgenticMemoryKgAssertionDraft,
	type AgenticMemoryKgProjectionBundle,
	type AgenticMemoryKgProjectionBundleOptions,
	type AgenticMemoryKgProjectionCursor,
	type AgenticMemoryKgProjectionError,
	type AgenticMemoryKgProjectionErrorCode,
	type AgenticMemoryKgProjectionSnapshot,
	type AgenticMemoryKgProjectionStatus,
	type AgenticMemoryKgProjectionStatusState,
	type AgenticMemoryKind,
	type AgenticMemoryPackedContext,
	type AgenticMemoryPackedContextEntry,
	type AgenticMemoryPersistenceLevel,
	type AgenticMemoryProjectionCursor,
	type AgenticMemoryProjectionSnapshot,
	type AgenticMemoryProposalAdmissionAudit,
	type AgenticMemoryProposalAdmissionCursor,
	type AgenticMemoryProposalAdmissionDecision,
	type AgenticMemoryProposalAdmissionDecisionState,
	type AgenticMemoryProposalAdmissionIssue,
	type AgenticMemoryProposalAdmissionOptions,
	type AgenticMemoryProposalAdmissionPolicy,
	type AgenticMemoryProposalAdmissionSnapshot,
	type AgenticMemoryProposalAdmissionStatus,
	type AgenticMemoryProposalAdmissionStatusState,
	type AgenticMemoryRecord,
	type AgenticMemoryRecordAdmission,
	type AgenticMemoryRecordAdmissionAuditEntry,
	type AgenticMemoryRecordAdmissionBundle,
	type AgenticMemoryRecordAdmissionBundleOptions,
	type AgenticMemoryRecordAdmissionCursor,
	type AgenticMemoryRecordAdmissionDecisionState,
	type AgenticMemoryRecordAdmissionPolicy,
	type AgenticMemoryRecordAdmissionSnapshot,
	type AgenticMemoryRecordAdmissionStatus,
	type AgenticMemoryRecordAdmissionStatusState,
	type AgenticMemoryRecordApplicationAuditEntry,
	type AgenticMemoryRecordApplicationBundle,
	type AgenticMemoryRecordApplicationBundleOptions,
	type AgenticMemoryRecordApplicationCursor,
	type AgenticMemoryRecordApplicationDecision,
	type AgenticMemoryRecordApplicationDecisionState,
	type AgenticMemoryRecordApplicationEvidence,
	type AgenticMemoryRecordApplicationMaterialFrame,
	type AgenticMemoryRecordApplicationMaterialIdentity,
	type AgenticMemoryRecordApplicationMaterialIdentityAlgorithm,
	type AgenticMemoryRecordApplicationOperation,
	type AgenticMemoryRecordApplicationOperationCursor,
	type AgenticMemoryRecordApplicationOperationStatus,
	type AgenticMemoryRecordApplicationOptions,
	type AgenticMemoryRecordApplicationPolicy,
	type AgenticMemoryRecordApplicationPriorEvidence,
	type AgenticMemoryRecordApplicationReasonCode,
	type AgenticMemoryRecordApplicationSnapshot,
	type AgenticMemoryRecordApplicationStatus,
	type AgenticMemoryRecordApplicationStatusState,
	type AgenticMemoryRecordCandidateMaterial,
	type AgenticMemoryRecordFrame,
	type AgenticMemoryRecordMetadata,
	type AgenticMemoryRecordProposal,
	type AgenticMemoryRetentionBundle,
	type AgenticMemoryRetentionBundleOptions,
	type AgenticMemoryRetentionCommand,
	type AgenticMemoryRetentionCursor,
	type AgenticMemoryRetentionError,
	type AgenticMemoryRetentionErrorCode,
	type AgenticMemoryRetentionSnapshot,
	type AgenticMemoryRetentionStatus,
	type AgenticMemoryScope,
	type AgenticMemorySourceProjection,
	type AgenticMemoryStatus,
	type AgenticMemoryStatusState,
	type AgenticMemoryStrictJsonValue,
	admitAgenticMemoryRecordProposals,
	agenticMemoryBundle,
	agenticMemoryConsolidationApplicationBundle,
	agenticMemoryConsolidationBundle,
	agenticMemoryContextPackingBundle,
	agenticMemoryKgProjectionBundle,
	agenticMemoryRecordAdmissionBundle,
	agenticMemoryRecordApplicationBundle,
	agenticMemoryRecordCodec,
	agenticMemoryRecordFrame,
	agenticMemoryRecordFrameCodec,
	agenticMemoryRetentionBundle,
	applyAgenticMemoryRecordAdmissions,
	assertAgenticMemoryRecordFrame,
	type KnowledgeAssertion,
	type KnowledgeAssertionObject,
	type KnowledgeAssertionSubject,
} from "./agentic-memory/index.js";

export {
	type AgenticWorkItemMemoryBridgeAuditEntry,
	type AgenticWorkItemMemoryBridgeBundle,
	type AgenticWorkItemMemoryBridgeBundleOptions,
	type AgenticWorkItemMemoryBridgeCursor,
	type AgenticWorkItemMemoryBridgeInput,
	type AgenticWorkItemMemoryBridgeIssue,
	type AgenticWorkItemMemoryBridgeResult,
	type AgenticWorkItemMemoryBridgeStatus,
	type AgenticWorkItemMemoryBridgeStatusState,
	type AgenticWorkItemMemoryContextFact,
	type AgenticWorkItemMemoryDataSelector,
	type AgenticWorkItemMemoryFieldPath,
	type AgenticWorkItemMemoryInputLane,
	type AgenticWorkItemMemoryMappingPolicy,
	type AgenticWorkItemMemoryRecordCandidate,
	type AgenticWorkItemMemoryRecordMappingRule,
	type AgenticWorkItemMemoryScoreMappingRule,
	agenticWorkItemMemoryBridgeBundle,
	mapAgenticWorkItemMemoryBridge,
} from "./agentic-work-item-memory/index.js";

export {
	type CapabilityAdmission,
	type CapabilityAdmissionBundle,
	type CapabilityAdmissionDecision,
	type CapabilityAdmissionOutcome,
	type CapabilityAdmissionPolicy,
	type CapabilityAdmissionProposal,
	type CapabilityAdmissionState,
	type CapabilityAdmissionStatus,
	type CapabilityAdmissionViews,
	capabilityAdmissionProjector,
	capabilityAdmissionProposal,
} from "./capability-admission.js";

export {
	analyzeAndMeasure,
	type BaseContentBlock,
	BLOCKS_MEASUREMENT_KIND,
	type BlockAdapters,
	type BlockAdaptersProviderOptions,
	type BlockMeasurementProviderOptions,
	type BlocksMeasurement,
	blockAdaptersProvider,
	blockMeasurementProvider,
	CapabilityMeasureAdapter,
	type CapabilityTextMeasurementsOptions,
	CellMeasureAdapter,
	type CellMeasureAdapterOptions,
	type CellTextMeasurementsOptions,
	type CircleObstacle,
	type ComputeFlowLinesOptions,
	type ContentBlock,
	capabilityTextMeasurements,
	carveTextLineSlots,
	cellTextMeasurements,
	circleIntervalForBand,
	computeBlockFlow,
	computeCharPositions,
	computeFlowLines,
	computeLineBreaks,
	computeTotalHeight,
	type FlowColumns,
	type FlowContainer,
	type FlowLinesResult,
	IMAGE_SIZE_MEASUREMENT_KIND,
	type ImageContentBlock,
	type ImageMeasurer,
	ImageSizeAdapter,
	type ImageSizeLookup,
	type ImageSizeMeasurementsOptions,
	type ImageSizeMeasurementTarget,
	InjectedMeasureAdapter,
	type InjectedMeasureAdapterOptions,
	type InjectedTextMeasurementsOptions,
	imageSizeMeasurements,
	injectedTextMeasurements,
	type LayoutCursor,
	type LayoutLine,
	type LayoutNextLineContext,
	type LayoutNextLineResult,
	type LineBreaksResult,
	layoutNextLine,
	type MeasureBlockOptions,
	type MeasuredBlock,
	type MeasureFn,
	type MeasurementAdapter,
	type MeasurementFact,
	type MeasurementIssue,
	type MeasurementReadiness,
	type MeasurementResult,
	type Measurements,
	type MergeMeasurementsOptions,
	measureBlock,
	measureBlocks,
	mergeMeasurements,
	type Obstacle,
	type PositionedBlock,
	type PositionedLine,
	PrecomputedMeasureAdapter,
	type PrecomputedMeasureAdapterOptions,
	type PrecomputedTextMeasurementsOptions,
	type PreparedSegment,
	precomputedTextMeasurements,
	READINESS_MEASUREMENT_KIND,
	type ReactiveBlockLayoutBundle,
	type ReactiveBlockLayoutOptions,
	type ReactiveFlowLayoutBundle,
	type ReactiveFlowLayoutOptions,
	type ReactiveLayoutBundle,
	type ReactiveLayoutOptions,
	type ReadinessMeasurementsOptions,
	type ReadinessTextMeasurementsOptions,
	type RectObstacle,
	reactiveBlockLayout,
	reactiveFlowLayout,
	reactiveLayout,
	readinessMeasurements,
	readinessTextMeasurements,
	rectIntervalForBand,
	type SegmentAdapter,
	type SegmentBreakKind,
	type SegmentInfo,
	type SegmentMeasureStats,
	type Size,
	SVG_BOUNDS_MEASUREMENT_KIND,
	SvgBoundsAdapter,
	type SvgBoundsMeasurementsOptions,
	type SvgBoundsMeasurementTarget,
	type SvgContentBlock,
	type SvgMeasurer,
	svgBoundsMeasurements,
	TEXT_SEGMENTS_MEASUREMENT_KIND,
	type TextContentBlock,
	type TextMeasureCapability,
	type TextMeasurementProviderOptions,
	type TextSegmentsMeasurement,
	textMeasurementProvider,
} from "./reactive-layout/index.js";
