/**
 * Horizontal reusable graph patterns.
 *
 * Former preset material lands here only when it is not a vertical solution
 * and has been re-derived onto clean-slate APIs.
 */

export {
	type EventFlowAuditRecord,
	type EventFlowBundle,
	type EventFlowHighWater,
	type EventFlowOptions,
	type EventFlowProjectionBundle,
	type EventFlowProjectionFrame,
	type EventFlowProjectionOptions,
	type EventFlowProjectionStatus,
	type EventFlowRecord,
	type EventFlowSource,
	type EventFlowSourceHighWater,
	type EventFlowSourceInput,
	type EventFlowSourceRef,
	type EventFlowStatus,
	eventFlow,
	eventFlowProjection,
} from "./event-flow.js";
export {
	type ProfileSummary,
	type ProfileSummaryNode,
	profileSummary,
} from "./inspection.js";
export {
	type AdmissionFilter,
	type AdmissionScore3DOptions,
	type AdmissionScoredOptions,
	type AdmissionScores,
	type AdmissionThresholds,
	admissionFilter3D,
	admissionScored,
	type CollectionEntry,
	type CollectionScoreFn,
	cosineSimilarity,
	type DecayPolicy,
	type FactId,
	type FactStore,
	filterMemoryFragments,
	isMemoryFragment,
	type KnowledgeAssertion,
	type KnowledgeAssertionObject,
	type KnowledgeAssertionStrictJsonValue,
	type KnowledgeAssertionSubject,
	type MemoryAnswer,
	type MemoryFragment,
	type MemoryFragmentValidation,
	type MemoryQuery,
	memoryFragmentMatchesQuery,
	memoryFragmentValidAt,
	type OutcomeSignal,
	type RankedCollectionEntry,
	type RetrievalEntry,
	type RetrievalQuery,
	type RetrievalTrace,
	type ScoringPolicy,
	type ShardByTenantConfig,
	type ShardByTenantOptions,
	type ShardKey,
	type StoreReadHandle,
	shardByTenant,
	type VectorSearchResult,
	validateMemoryFragment,
} from "./semantic-memory.js";
export {
	type KnowledgeGraphCursor,
	type KnowledgeGraphEntity,
	type KnowledgeGraphError,
	type KnowledgeGraphErrorCode,
	type KnowledgeGraphIndex,
	type KnowledgeGraphPolicy,
	type KnowledgeGraphReducerBundle,
	type KnowledgeGraphReducerBundleOptions,
	type KnowledgeGraphRelation,
	type KnowledgeGraphSnapshot,
	type KnowledgeGraphStatus,
	type KnowledgeGraphStatusState,
	type KnowledgeGraphTopic,
	knowledgeGraphReducerBundle,
	type MemoryRetrievalBundle,
	type MemoryRetrievalBundleOptions,
	type MemoryRetrievalCursor,
	type MemoryRetrievalError,
	type MemoryRetrievalErrorCode,
	type MemoryRetrievalFact,
	type MemoryRetrievalIndex,
	type MemoryRetrievalQuery,
	type MemoryRetrievalSnapshot,
	type MemoryRetrievalStatus,
	type MemoryRetrievalStatusState,
	memoryRetrievalBundle,
} from "./semantic-memory-graph.js";
