import starlight from "@astrojs/starlight";
import { defineConfig } from "astro/config";

/** GitHub Project Pages: set to `/repo-name/` (trailing slash). Root site: `'/'`. */
const base = process.env.ASTRO_BASE_PATH ?? "/";

export default defineConfig({
	site: process.env.ASTRO_SITE_URL ?? "https://example.invalid",
	base,
	integrations: [
		starlight({
			title: "GraphReFly",
			description: "Reactive graph protocol for human + LLM co-operation — TypeScript and Python.",
			components: {
				Header: "./src/components/Header.astro",
				MobileMenuFooter: "./src/components/MobileMenuFooter.astro",
				Sidebar: "./src/components/Sidebar.astro",
			},
			customCss: ["./src/styles/custom.css"],
			head: [
				{ tag: "link", attrs: { rel: "preconnect", href: "https://fonts.googleapis.com" } },
				{
					tag: "link",
					attrs: { rel: "preconnect", href: "https://fonts.gstatic.com", crossorigin: "" },
				},
			],
			social: [
				{
					icon: "github",
					label: "graphrefly-ts",
					href: "https://github.com/graphrefly/graphrefly-ts",
				},
			],
			sidebar: [
				{
					label: "Protocol",
					items: [{ label: "Specification", link: "/spec" }],
				},
				{
					label: "API — Core",
					items: [
						{ label: "node()", link: "/api/node" },
						{ label: "state()", link: "/api/state" },
						{ label: "derived()", link: "/api/derived" },
						{ label: "producer()", link: "/api/producer" },
						{ label: "effect()", link: "/api/effect" },
						{ label: "pipe()", link: "/api/pipe" },
						{ label: "batch()", link: "/api/batch" },
						{ label: "dynamicNode()", link: "/api/dynamicNode" },
					],
				},
				{
					label: "API — Sources",
					collapsed: true,
					items: [
						{ label: "fromTimer()", link: "/api/fromTimer" },
						{ label: "fromCron()", link: "/api/fromCron" },
						{ label: "fromEvent()", link: "/api/fromEvent" },
						{ label: "fromWebhook()", link: "/api/fromWebhook" },
						{ label: "fromPromise()", link: "/api/fromPromise" },
						{ label: "fromIter()", link: "/api/fromIter" },
						{ label: "fromAsyncIter()", link: "/api/fromAsyncIter" },
						{ label: "fromAny()", link: "/api/fromAny" },
						{ label: "of()", link: "/api/of" },
						{ label: "empty()", link: "/api/empty" },
						{ label: "never()", link: "/api/never" },
						{ label: "throwError()", link: "/api/throwError" },
						{ label: "forEach()", link: "/api/forEach" },
						{ label: "toArray()", link: "/api/toArray" },
						{ label: "firstValueFrom()", link: "/api/firstValueFrom" },
						{ label: "cached()", link: "/api/cached" },
						{ label: "replay()", link: "/api/replay" },
						{ label: "shareReplay()", link: "/api/shareReplay" },
						{ label: "share()", link: "/api/share" },
					],
				},
				{
					label: "API — Operators",
					collapsed: true,
					items: [
						{ label: "map()", link: "/api/map" },
						{ label: "filter()", link: "/api/filter" },
						{ label: "scan()", link: "/api/scan" },
						{ label: "reduce()", link: "/api/reduce" },
						{ label: "take()", link: "/api/take" },
						{ label: "skip()", link: "/api/skip" },
						{ label: "first()", link: "/api/first" },
						{ label: "last()", link: "/api/last" },
						{ label: "find()", link: "/api/find" },
						{ label: "elementAt()", link: "/api/elementAt" },
						{ label: "takeWhile()", link: "/api/takeWhile" },
						{ label: "takeUntil()", link: "/api/takeUntil" },
						{ label: "startWith()", link: "/api/startWith" },
						{ label: "tap()", link: "/api/tap" },
						{ label: "distinctUntilChanged()", link: "/api/distinctUntilChanged" },
						{ label: "pairwise()", link: "/api/pairwise" },
					],
				},
				{
					label: "API — Combinators",
					collapsed: true,
					items: [
						{ label: "combine()", link: "/api/combine" },
						{ label: "combineLatest()", link: "/api/combineLatest" },
						{ label: "withLatestFrom()", link: "/api/withLatestFrom" },
						{ label: "merge()", link: "/api/merge" },
						{ label: "zip()", link: "/api/zip" },
						{ label: "concat()", link: "/api/concat" },
						{ label: "race()", link: "/api/race" },
					],
				},
				{
					label: "API — Async & timers",
					collapsed: true,
					items: [
						{ label: "switchMap()", link: "/api/switchMap" },
						{ label: "exhaustMap()", link: "/api/exhaustMap" },
						{ label: "concatMap()", link: "/api/concatMap" },
						{ label: "mergeMap()", link: "/api/mergeMap" },
						{ label: "flatMap()", link: "/api/flatMap" },
						{ label: "delay()", link: "/api/delay" },
						{ label: "debounce()", link: "/api/debounce" },
						{ label: "debounceTime()", link: "/api/debounceTime" },
						{ label: "throttle()", link: "/api/throttle" },
						{ label: "throttleTime()", link: "/api/throttleTime" },
						{ label: "sample()", link: "/api/sample" },
						{ label: "audit()", link: "/api/audit" },
						{ label: "timeout()", link: "/api/timeout" },
						{ label: "buffer()", link: "/api/buffer" },
						{ label: "bufferCount()", link: "/api/bufferCount" },
						{ label: "bufferTime()", link: "/api/bufferTime" },
						{ label: "window()", link: "/api/window" },
						{ label: "windowCount()", link: "/api/windowCount" },
						{ label: "windowTime()", link: "/api/windowTime" },
						{ label: "interval()", link: "/api/interval" },
						{ label: "repeat()", link: "/api/repeat" },
						{ label: "pausable()", link: "/api/pausable" },
						{ label: "rescue()", link: "/api/rescue" },
						{ label: "catchError()", link: "/api/catchError" },
						{ label: "gate()", link: "/api/gate" },
					],
				},
				{
					label: "API — Resilience & checkpoints",
					collapsed: true,
					items: [
						{ label: "constant()", link: "/api/constant" },
						{ label: "linear()", link: "/api/linear" },
						{ label: "exponential()", link: "/api/exponential" },
						{ label: "fibonacci()", link: "/api/fibonacci" },
						{ label: "resolveBackoffPreset()", link: "/api/resolveBackoffPreset" },
						{ label: "retry()", link: "/api/retry" },
						{ label: "circuitBreaker()", link: "/api/circuitBreaker" },
						{ label: "CircuitOpenError", link: "/api/CircuitOpenError" },
						{ label: "tokenBucket()", link: "/api/tokenBucket" },
						{ label: "tokenTracker()", link: "/api/tokenTracker" },
						{ label: "rateLimiter()", link: "/api/rateLimiter" },
						{ label: "withBreaker()", link: "/api/withBreaker" },
						{ label: "withStatus()", link: "/api/withStatus" },
						{ label: "MemoryCheckpointAdapter", link: "/api/MemoryCheckpointAdapter" },
						{ label: "DictCheckpointAdapter", link: "/api/DictCheckpointAdapter" },
						{ label: "FileCheckpointAdapter", link: "/api/FileCheckpointAdapter" },
						{ label: "SqliteCheckpointAdapter", link: "/api/SqliteCheckpointAdapter" },
						{ label: "saveGraphCheckpoint()", link: "/api/saveGraphCheckpoint" },
						{ label: "restoreGraphCheckpoint()", link: "/api/restoreGraphCheckpoint" },
						{ label: "checkpointNodeValue()", link: "/api/checkpointNodeValue" },
						{ label: "saveGraphCheckpointIndexedDb()", link: "/api/saveGraphCheckpointIndexedDb" },
						{ label: "restoreGraphCheckpointIndexedDb()", link: "/api/restoreGraphCheckpointIndexedDb" },
						{ label: "fromIDBRequest()", link: "/api/fromIDBRequest" },
						{ label: "fromIDBTransaction()", link: "/api/fromIDBTransaction" },
					],
				},
				{
					label: "API — Data structures",
					collapsed: true,
					items: [
						{ label: "reactiveMap()", link: "/api/reactiveMap" },
						{ label: "reactiveLog()", link: "/api/reactiveLog" },
						{ label: "logSlice()", link: "/api/logSlice" },
						{ label: "reactiveIndex()", link: "/api/reactiveIndex" },
						{ label: "reactiveList()", link: "/api/reactiveList" },
						{ label: "pubsub()", link: "/api/pubsub" },
						{ label: "verifiable()", link: "/api/verifiable" },
						{ label: "distill()", link: "/api/distill" },
					],
				},
				{
					label: "API — Backpressure & flow",
					collapsed: true,
					items: [
						{ label: "createWatermarkController()", link: "/api/createWatermarkController" },
					],
				},
				{
					label: "API — Observable interop",
					collapsed: true,
					items: [
						{ label: "toObservable()", link: "/api/toObservable" },
						{ label: "toMessages$()", link: "/api/toMessages$" },
						{ label: "observeNode$()", link: "/api/observeNode$" },
						{ label: "observeGraph$()", link: "/api/observeGraph$" },
					],
				},
				{
					label: "API — Internals",
					collapsed: true,
					items: [
						{ label: "isBatching()", link: "/api/isBatching" },
						{ label: "partitionForBatch()", link: "/api/partitionForBatch" },
						{ label: "emitWithBatch()", link: "/api/emitWithBatch" },
						{ label: "metaSnapshot()", link: "/api/metaSnapshot" },
						{ label: "describeNode()", link: "/api/describeNode" },
						{ label: "policy()", link: "/api/policy" },
						{ label: "GuardDenied", link: "/api/GuardDenied" },
						{ label: "accessHintForGuard()", link: "/api/accessHintForGuard" },
						{ label: "reachable()", link: "/api/reachable" },
						{ label: "parseCron()", link: "/api/parseCron" },
						{ label: "matchesCron()", link: "/api/matchesCron" },
						{ label: "decorrelatedJitter()", link: "/api/decorrelatedJitter" },
						{ label: "withMaxAttempts()", link: "/api/withMaxAttempts" },
						{ label: "resolveBackoffPreset()", link: "/api/resolveBackoffPreset" },
					],
				},
				{
					label: "API — Layout engine",
					collapsed: true,
					items: [
						{ label: "reactiveLayout()", link: "/api/reactiveLayout" },
						{ label: "reactiveBlockLayout()", link: "/api/reactiveBlockLayout" },
						{ label: "analyzeAndMeasure()", link: "/api/analyzeAndMeasure" },
						{ label: "computeLineBreaks()", link: "/api/computeLineBreaks" },
						{ label: "computeCharPositions()", link: "/api/computeCharPositions" },
					],
				},
				{
					label: "API — Worker bridge",
					collapsed: true,
					items: [
						{ label: "workerBridge()", link: "/api/workerBridge" },
						{ label: "workerSelf()", link: "/api/workerSelf" },
						{ label: "createTransport()", link: "/api/createTransport" },
					],
				},
				{
					label: "API — Graph",
					collapsed: true,
					items: [{ label: "Graph", link: "/api/Graph" }],
				},
			],
		}),
	],
});
