import starlight from "@astrojs/starlight";
import { defineConfig } from "astro/config";
import starlightBlog from "starlight-blog";

/** GitHub Project Pages: set to `/repo-name/` (trailing slash). Root site: `'/'`. */
const base = process.env.ASTRO_BASE_PATH ?? "/";

export default defineConfig({
	site: process.env.ASTRO_SITE_URL ?? "https://example.invalid",
	base,
	integrations: [
		starlight({
			plugins: [
				starlightBlog({
					title: "Blog",
					authors: {
						david: {
							name: "David Chen",
							title: "GraphReFly creator",
						},
					},
				}),
			],
			title: "GraphReFly",
			description: "Reactive harness layer for agent workflows. Describe automations in plain language, trace every decision, enforce policies, persist checkpoints. Zero dependencies.",
			components: {
				Header: "./src/components/Header.astro",
				Footer: "./src/components/Footer.astro",
				MobileMenuFooter: "./src/components/MobileMenuFooter.astro",
				Sidebar: "./src/components/Sidebar.astro",
			},
			customCss: ["./src/styles/custom.css"],
			head: [
				{ tag: "link", attrs: { rel: "preconnect", href: "https://fonts.googleapis.com" } },
				{
					tag: "link",
					attrs: { rel: "preconnect", href: "https://fonts.gstatic.com", crossorigin: "" },
				},
				{
					tag: "script",
					content: `(function(){var p=location.pathname,l=p.toLowerCase();if(p!==l)location.replace(l+location.search+location.hash)})()`,
				},
			],
			social: [
				{
					icon: "github",
					label: "graphrefly-ts",
					href: "https://github.com/graphrefly/graphrefly-ts",
				},
			],
			sidebar: [
				{
					label: "Protocol",
					items: [{ label: "Specification", link: "/spec" }],
				},
				{
					label: "API — Core",
						items: [
							{ label: "node()", link: "/api/node" },
							{ label: "state()", link: "/api/state" },
							{ label: "derived()", link: "/api/derived" },
							{ label: "producer()", link: "/api/producer" },
							{ label: "effect()", link: "/api/effect" },
							{ label: "pipe()", link: "/api/pipe" },
							{ label: "batch()", link: "/api/batch" },
							{ label: "dynamicNode()", link: "/api/dynamicnode" },
						],
					},
					{
						label: "Sources",
						collapsed: true,
						items: [
							{ label: "fromTimer()", link: "/api/fromtimer" },
							{ label: "fromCron()", link: "/api/fromcron" },
							{ label: "fromEvent()", link: "/api/fromevent" },
							{ label: "fromWebhook()", link: "/api/fromwebhook" },
							{ label: "fromPromise()", link: "/api/frompromise" },
							{ label: "fromIter()", link: "/api/fromiter" },
							{ label: "fromAsyncIter()", link: "/api/fromasynciter" },
							{ label: "fromAny()", link: "/api/fromany" },
							{ label: "of()", link: "/api/of" },
							{ label: "empty()", link: "/api/empty" },
							{ label: "never()", link: "/api/never" },
							{ label: "throwError()", link: "/api/throwerror" },
							{ label: "forEach()", link: "/api/foreach" },
							{ label: "toArray()", link: "/api/toarray" },
							{ label: "firstValueFrom()", link: "/api/firstvaluefrom" },
							{ label: "cached()", link: "/api/cached" },
							{ label: "replay()", link: "/api/replay" },
							{ label: "shareReplay()", link: "/api/sharereplay" },
							{ label: "share()", link: "/api/share" },
						],
					},
					{
						label: "Operators",
						collapsed: true,
						items: [
							{ label: "map()", link: "/api/map" },
							{ label: "filter()", link: "/api/filter" },
							{ label: "scan()", link: "/api/scan" },
							{ label: "reduce()", link: "/api/reduce" },
							{ label: "take()", link: "/api/take" },
							{ label: "skip()", link: "/api/skip" },
							{ label: "first()", link: "/api/first" },
							{ label: "last()", link: "/api/last" },
							{ label: "find()", link: "/api/find" },
							{ label: "elementAt()", link: "/api/elementat" },
							{ label: "takeWhile()", link: "/api/takewhile" },
							{ label: "takeUntil()", link: "/api/takeuntil" },
							{ label: "startWith()", link: "/api/startwith" },
							{ label: "tap()", link: "/api/tap" },
							{ label: "distinctUntilChanged()", link: "/api/distinctuntilchanged" },
							{ label: "pairwise()", link: "/api/pairwise" },
						],
					},
					{
						label: "Combinators",
						collapsed: true,
						items: [
							{ label: "combine()", link: "/api/combine" },
							{ label: "combineLatest()", link: "/api/combinelatest" },
							{ label: "withLatestFrom()", link: "/api/withlatestfrom" },
							{ label: "merge()", link: "/api/merge" },
							{ label: "zip()", link: "/api/zip" },
							{ label: "concat()", link: "/api/concat" },
							{ label: "race()", link: "/api/race" },
						],
					},
					{
						label: "Async & timers",
						collapsed: true,
						items: [
							{ label: "switchMap()", link: "/api/switchmap" },
							{ label: "exhaustMap()", link: "/api/exhaustmap" },
							{ label: "concatMap()", link: "/api/concatmap" },
							{ label: "mergeMap()", link: "/api/mergemap" },
							{ label: "flatMap()", link: "/api/flatmap" },
							{ label: "delay()", link: "/api/delay" },
							{ label: "debounce()", link: "/api/debounce" },
							{ label: "debounceTime()", link: "/api/debouncetime" },
							{ label: "throttle()", link: "/api/throttle" },
							{ label: "throttleTime()", link: "/api/throttletime" },
							{ label: "sample()", link: "/api/sample" },
							{ label: "audit()", link: "/api/audit" },
							{ label: "timeout()", link: "/api/timeout" },
							{ label: "buffer()", link: "/api/buffer" },
							{ label: "bufferCount()", link: "/api/buffercount" },
							{ label: "bufferTime()", link: "/api/buffertime" },
							{ label: "window()", link: "/api/window" },
							{ label: "windowCount()", link: "/api/windowcount" },
							{ label: "windowTime()", link: "/api/windowtime" },
							{ label: "interval()", link: "/api/interval" },
							{ label: "repeat()", link: "/api/repeat" },
							{ label: "pausable()", link: "/api/pausable" },
							{ label: "rescue()", link: "/api/rescue" },
							{ label: "catchError()", link: "/api/catcherror" },
							{ label: "gate()", link: "/api/gate" },
						],
					},
					{
						label: "Resilience & checkpoints",
						collapsed: true,
						items: [
							{ label: "constant()", link: "/api/constant" },
							{ label: "linear()", link: "/api/linear" },
							{ label: "exponential()", link: "/api/exponential" },
							{ label: "fibonacci()", link: "/api/fibonacci" },
							{ label: "resolveBackoffPreset()", link: "/api/resolvebackoffpreset" },
							{ label: "retry()", link: "/api/retry" },
							{ label: "circuitBreaker()", link: "/api/circuitbreaker" },
							{ label: "CircuitOpenError", link: "/api/circuitopenerror" },
							{ label: "tokenBucket()", link: "/api/tokenbucket" },
							{ label: "tokenTracker()", link: "/api/tokentracker" },
							{ label: "rateLimiter()", link: "/api/ratelimiter" },
							{ label: "withBreaker()", link: "/api/withbreaker" },
							{ label: "withStatus()", link: "/api/withstatus" },
							{ label: "MemoryCheckpointAdapter", link: "/api/memorycheckpointadapter" },
							{ label: "DictCheckpointAdapter", link: "/api/dictcheckpointadapter" },
							{ label: "FileCheckpointAdapter", link: "/api/filecheckpointadapter" },
							{ label: "SqliteCheckpointAdapter", link: "/api/sqlitecheckpointadapter" },
							{ label: "saveGraphCheckpoint()", link: "/api/savegraphcheckpoint" },
							{ label: "restoreGraphCheckpoint()", link: "/api/restoregraphcheckpoint" },
							{ label: "checkpointNodeValue()", link: "/api/checkpointnodevalue" },
							{ label: "saveGraphCheckpointIndexedDb()", link: "/api/savegraphcheckpointindexeddb" },
							{ label: "restoreGraphCheckpointIndexedDb()", link: "/api/restoregraphcheckpointindexeddb" },
							{ label: "fromIDBRequest()", link: "/api/fromidbrequest" },
							{ label: "fromIDBTransaction()", link: "/api/fromidbtransaction" },
						],
					},
					{
						label: "Data structures",
						collapsed: true,
						items: [
							{ label: "reactiveMap()", link: "/api/reactivemap" },
							{ label: "reactiveLog()", link: "/api/reactivelog" },
							{ label: "logSlice()", link: "/api/logslice" },
							{ label: "reactiveIndex()", link: "/api/reactiveindex" },
							{ label: "reactiveList()", link: "/api/reactivelist" },
							{ label: "pubsub()", link: "/api/pubsub" },
							{ label: "verifiable()", link: "/api/verifiable" },
							{ label: "distill()", link: "/api/distill" },
						],
					},
					{
						label: "Backpressure & flow",
						collapsed: true,
						items: [
							{ label: "createWatermarkController()", link: "/api/createwatermarkcontroller" },
						],
					},
					{
						label: "Observable interop",
						collapsed: true,
						items: [
							{ label: "toObservable()", link: "/api/toobservable" },
						],
					},
					{
						label: "Internals",
						collapsed: true,
						items: [
							{ label: "isBatching()", link: "/api/isbatching" },
							{ label: "partitionForBatch()", link: "/api/partitionforbatch" },
							{ label: "downWithBatch()", link: "/api/downwithbatch" },
							{ label: "policy()", link: "/api/policy" },
							{ label: "GuardDenied", link: "/api/guarddenied" },
							{ label: "accessHintForGuard()", link: "/api/accesshintforguard" },
							{ label: "reachable()", link: "/api/reachable" },
							{ label: "parseCron()", link: "/api/parsecron" },
							{ label: "matchesCron()", link: "/api/matchescron" },
							{ label: "decorrelatedJitter()", link: "/api/decorrelatedjitter" },
							{ label: "withMaxAttempts()", link: "/api/withmaxattempts" },
							{ label: "resolveBackoffPreset()", link: "/api/resolvebackoffpreset" },
						],
					},
					{
						label: "Layout engine",
						collapsed: true,
						items: [
							{ label: "reactiveLayout()", link: "/api/reactivelayout" },
							{ label: "reactiveBlockLayout()", link: "/api/reactiveblocklayout" },
							{ label: "analyzeAndMeasure()", link: "/api/analyzeandmeasure" },
							{ label: "computeLineBreaks()", link: "/api/computelinebreaks" },
							{ label: "computeCharPositions()", link: "/api/computecharpositions" },
						],
					},
					{
						label: "Worker bridge",
						collapsed: true,
						items: [
							{ label: "workerBridge()", link: "/api/workerbridge" },
							{ label: "workerSelf()", link: "/api/workerself" },
							{ label: "createTransport()", link: "/api/createtransport" },
						],
					},
					{
						label: "Graph",
						collapsed: true,
						items: [{ label: "Graph", link: "/api/graph" }],
					},
				{
					label: "Comparisons",
					items: [
						{ label: "vs Zustand", link: "/comparisons/zustand" },
						{ label: "vs Jotai", link: "/comparisons/jotai" },
						{ label: "vs RxJS", link: "/comparisons/rxjs" },
						{ label: "vs LangGraph.js", link: "/comparisons/langgraph" },
						{ label: "vs Vercel AI SDK", link: "/comparisons/vercel-ai-sdk" },
						{ label: "vs n8n", link: "/comparisons/n8n" },
						{ label: "vs Apache Airflow", link: "/comparisons/airflow" },
					],
				},
				{
					label: "Recipes",
					items: [
						{ label: "From callbag-recharge", link: "/recipes/from-callbag-recharge" },
						{ label: "NestJS Integration", link: "/recipes/nestjs-integration" },
					],
				},
			],
		}),
	],
});
